### ISSUE TITLE
Verse block appears un-styled

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentytwo#100]
**Describe the solution you'd like**
The verse block currently appears un-styled: 

<img width="1150" alt="Screen Shot 2021-10-13 at 9 26 57 AM" src="https://user-images.githubusercontent.com/5375500/137141977-90c8002d-4dd8-42aa-9878-c09684328131.png">

Do we want to add anything here?

**Comment by kjellr** [comment]
I think that's fine — verse should look just like a paragraph except it would retain line breaks.
