### ISSUE TITLE
File block download button needs styles

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentytwo#101]
**Describe the solution you'd like**
The file block's download button is not styled: 

<img width="404" alt="Screen Shot 2021-10-13 at 9 41 11 AM" src="https://user-images.githubusercontent.com/5375500/137144588-20f06515-8717-46c7-86d4-513db5d9cd65.png">

The button should match the theme's default button styles. Can button styling of the file block be done with theme.json yet?

**Comment by MaggieCabrera** [comment]
> The button should match the theme's default button styles. Can button styling of the file block be done with theme.json yet?

AFAIK no, it would fall under this: https://github.com/WordPress/gutenberg/issues/29167

**Comment by kjellr** [comment]
Fixed by #235.
