### ISSUE TITLE
Pullquote may need additional styling

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentytwo#102]
**Is your feature request related to a problem? Please describe.**
Currently the pullquote appears like this:

<img width="723" alt="Screen Shot 2021-10-13 at 9 46 09 AM" src="https://user-images.githubusercontent.com/5375500/137145839-7e0aab33-ed01-4bb2-a149-72548e244e63.png">

Should we make any adjustments by default, e.g. adjusting the spacing and line height?

**Comment by kjellr** [comment]
I opened #128 to address the border width. I'd also like to adjust the font-family as described in https://github.com/WordPress/gutenberg/issues/35735, but that's not possible yet. So let's keep this open for now.

**Comment by kjellr** [comment]
Since https://github.com/WordPress/gutenberg/issues/35735 is not going to happen before 5.9, I'm going to close this issue for now.
