### ISSUE TITLE
Query pagination appears incorrectly positioned

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#106]
The default query pagination appears to behave very oddly. Lots of misaligned items: 

<img width="1286" alt="Screen Shot 2021-10-13 at 12 43 57 PM" src="https://user-images.githubusercontent.com/1202812/137177430-04b8d77b-35bf-4527-ac99-069389988801.png">
<img width="1178" alt="Screen Shot 2021-10-13 at 12 44 04 PM" src="https://user-images.githubusercontent.com/1202812/137177434-78930d59-cd70-4a05-a3bc-0f22b663b018.png">
<img width="1092" alt="Screen Shot 2021-10-13 at 12 44 12 PM" src="https://user-images.githubusercontent.com/1202812/137177436-6b6a424e-f46f-4fc5-9fee-635355695ab8.png">

Here's how that's supposed to look, according to the comps: 

<img width="1074" alt="Screen Shot 2021-10-13 at 12 48 09 PM" src="https://user-images.githubusercontent.com/1202812/137177726-1d81629c-6bf2-4ac7-9d7c-c4f881f66238.png">

**Comment by luminuu** [comment]
Looks fine to me in the latest TT2 version and Gutenberg 11.7:

![Bildschirmfoto am 2021-10-15 um 12 02 42](https://user-images.githubusercontent.com/7585600/137470438-c13dee7b-ba21-46e0-80fe-ecc941d79f40.png)

**Comment by MaggieCabrera** [comment]
This is what I see with the latest from trunk:

First page:

<img width="1061" alt="Screenshot 2021-10-15 at 12 07 49" src="https://user-images.githubusercontent.com/3593343/137471253-1d5909d7-ce28-4a46-97bf-78a602086b86.png">

Pages in the middle:

<img width="1058" alt="Screenshot 2021-10-15 at 12 07 45" src="https://user-images.githubusercontent.com/3593343/137471257-0c05228a-9106-46b7-bb6e-4906b77835b7.png">

Last page:

<img width="1069" alt="Screenshot 2021-10-15 at 12 07 39" src="https://user-images.githubusercontent.com/3593343/137471259-a3d02779-b730-484a-830f-aadc360cb3aa.png">

this was already reported in GB too: https://github.com/WordPress/gutenberg/issues/34997

**Comment by kjellr** [comment]
Seems to be gone for me now. Thanks for testing! I'll close.
