### ISSUE TITLE
Text links need improved styles 

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#108]
From [the mockups](https://www.figma.com/file/76mfUcaK4QDlrXElk8MK3H/Twenty-Twenty-Two?node-id=729%3A4866): 

---

![image](https://user-images.githubusercontent.com/1202812/137189639-de952745-f237-41e4-b99e-e119e21a06b8.png)

---

- Links need more refined text-decoration styles, so that the thin font isn't paired with a [horribly thick underline](https://cloudup.com/czdjAkphnKr). (I think we could probably elevate this issue from "enhancement" to a "bug" because of this bullet). 
- Link underlines should become dotted on hover and in their active state.  
- Focus state should be dotted.
- The mockups indicate that large post titles should _not_ have underlines by default, but that their hover and active states should have a solid underline.

May end up being related to: #99 
Upstream issue: https://github.com/WordPress/gutenberg/issues/27075

**Comment by kjellr** [comment]
> Links need more refined text-decoration styles, so that the thin font isn't paired with a horribly thick underline. (I think we could probably elevate this issue from "enhancement" to a "bug" because of this bullet).

If we get desperate, this would take like two lines of CSS to fix: 

```
a {
    text-decoration-thickness: 1px;
    text-underline-offset: 0.25ch;
}
```

Before|After
---|--
<img width="566" alt="Screen Shot 2021-10-13 at 2 09 13 PM" src="https://user-images.githubusercontent.com/1202812/137190488-addbd5f5-61ef-4677-a544-8b299b0b0f5f.png">|<img width="561" alt="Screen Shot 2021-10-13 at 2 04 01 PM" src="https://user-images.githubusercontent.com/1202812/137190519-17416331-b6b8-41b7-8076-3bc3835ae6dc.png">

**Comment by jffng** [comment]
Regarding those two lines of CSS, I wonder if they will be supported via the theme.json elements API. 

In other words, should we be able to declare `styles.elements.link.typography.textDecorationThickness` and `.textUnderlineOffset`?

**Comment by gregrickaby** [comment]
@kjellr @jffng Could I pick this one up? I'll try using `theme.json` first, and fall back to CSS.

**Comment by kjellr** [comment]
You're welcome to give it a shot, @gregrickaby! Just know that this might be a little difficult to sort out. I'm really hesitant to use CSS (so far, we don't even enqueue `style.css` in the editor yet since it's not needed), but the mechanisms to make this happen in `theme.json` don't exist yet. The most ideal solution is to get those built into Gutenberg somehow as part of https://github.com/WordPress/gutenberg/issues/27075. There's been very little movement there yet, so this may end up being a little bit of a dead end.

**Comment by gregrickaby** [comment]
Good to know. I'll look for another issue then. 😅 

Appreciate the heads up @kjellr!

**Comment by carolinan** [comment]
Here is how to manipulate theme.json to include the thickness:
```
	"core/post-title": {
				"typography": {
					"fontFamily": "var(--wp--preset--font-family--source-serif-pro)",
					"fontWeight": "300",
					"lineHeight": "var(--wp--custom--typography--line-height--tiny)",
					"fontSize": "var(--wp--custom--typography--font-size--gigantic)"
				},
				"elements":{
					"link": {
						"typography": {
							"textDecoration": ";text-decoration-thickness: 1px; text-underline-offset: 0.25ch;"
						}
					}
				}
			},
```
The key is closing the textDecoration with the extra ;
![image](https://user-images.githubusercontent.com/7422055/140270944-c0068223-0268-45d5-8f6e-f3260f913550.png)

It's definitely hacky. Its also very small.
