### ISSUE TITLE
Consider caption design for gallery

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentytwentytwo#119]
I noticed that the gallery doesn't have a caption design but used the default one for the block. Perhaps it could be nice to have something that reflects the theme design and shows how to style captions?

![2021-10-15 at 20 05](https://user-images.githubusercontent.com/253067/137539850-36a65ac9-f6db-405c-a098-8fd639ef6753.png)

**Comment by kjellr** [comment]
Hey @karmatosed — given the theme's drive to use little to no custom CSS, I don't plan for us to include any non-standard caption styles. I'd love to see Gutenberg support more by default, but in the meantime I'm going to close for now.

**Comment by karmatosed** [comment]
@kjellr that makes sense - I shall go and bother that repo! :)
