### ISSUE TITLE
Determine strategy for block patterns

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#12]
In previous themes, block patterns were bundled directly with the theme itself. We should consider doing that here, but also keep an eye on Pattern Directory progress. Can we instead put these patterns in the directory?

In addition to opening these patterns up to users beyond this single theme, having our patterns in the directory would cut down our theme code considerably, ensure translation is handled automatically, and also make them easier to update on the fly. 

Related Gutenberg issue: https://github.com/WordPress/gutenberg/issues/35364

**Comment by jffng** [comment]
It appears that this will not be in 5.9, so should we close this one since we will have to bundle them with the theme? 

In any case, we can upload them to the patterns directory, even if we can't remove them from the theme.

**Comment by kjellr** [comment]
Yep, I think it's fine to close for now. 👍
