### ISSUE TITLE
Space between group block and cover when using dark background

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentytwentytwo#121]
This might be the nature of these blocks and is fixed by using a background. However, I wanted to report this as it feels unexpected to see. It can be closed out if decided it's just something have to accept due to the nature of the site editor.

If you have a group block and also a cover block, yet both are dark - you get this strange gap in-between due to block gap I presume.

![2021-10-15 at 20 13](https://user-images.githubusercontent.com/253067/137540608-faf87406-2470-40e1-abbf-60f562ad002e.png)

Whilst you can fix this by setting the background to dark, that might be something someone does setting their entire site ... causing a not great user experience.

## Possible solutions
One possible option could be to provide a 'dark' template which unless I am mistaken I didn't see. I suggest this if the gap is a hitch due to the limitations of the editor today.

**Comment by carolinan** [comment]
Both the header dark pattern and template part has an 8rem bottom margin.

```
<!-- wp:group {"align":"full","style":{"elements":{"link":{"color":{"text":"var:preset|color|background"}}},"spacing":{"padding":{"top":"0px","right":"max(1.25rem, 5vw)","left":"max(1.25rem, 5vw)","bottom":"8rem"},"margin":{"bottom":"8rem"}}},"backgroundColor":"foreground","textColor":"background","layout":{"inherit":true}} -->

<div class="wp-block-group alignfull has-background-color has-foreground-background-color has-text-color has-background has-link-color" style="padding-top:0px;padding-right:max(1.25rem, 5vw);padding-bottom:8rem;padding-left:max(1.25rem, 5vw);margin-bottom:8rem">
```

**Comment by kjellr** [comment]
That's right — the user can remove that from the header themselves. We need that padding to exist somewhere for the cases when the user isn't trying to accomplish this specific scenario. I think it's generally reasonable for it to exist where it is today. 

I'm going to close for now, but we can re-open if folks have a better solution.
