### ISSUE TITLE
Add header and footer template parts to theme.json

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentytwo#122]
When you select a template part in the site editor, and then choose "Replace", you have the option to place the header parts in the footer and vice versa.
Is this intentional?

If it is not intentional, assign the template part to the respective template area in theme.json.

Example:
```
	"templateParts": [
		{
			"name": "header",
			"area": "header"
		},
		{
			"name": "header-large-dark",
			"area": "header"
		}
]
```

**Comment by jffng** [comment]
Not intentional, we should do this: 

> assign the template part to the respective template area in theme.json.
