### ISSUE TITLE
Index: Sticky posts are showing when you view page 2 etc

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentytwo#126]
**Describe the bug**
The query loop in index.html is not set to` Inherit query from template`, so the sticky posts are shown on all pages when navigating through the paged results.

**To Reproduce**
1. Set the homepage to display latest posts.
2. Make sure your test install have sticky posts, and enough content to use the query pagination to open page two etc.
3. Go to page two or higher.
4. See that the sticky posts are showing on the top of every page.

**Expected behavior**
The sticky posts, (if they should show? They show now.), should only show on the first page.

**Comment by carolinan** [comment]
And because search and archive templates are not included, these are also broken and displaying incorrect results from index.html

**Comment by kjellr** [comment]
This sounds like a Gutenberg bug, right? I don't think the theme is doing anything specific to the query that would cause this.

**Comment by carolinan** [comment]
The default is to not inherit the query from template, it needs to be enabled.

**Comment by carolinan** [comment]
I assume the archive will be added later and it wont be using index?

**Comment by kjellr** [comment]
Yes, we need an archive page template that includes the Archive Title at the top. 

Sounds like we also need to ensure the `index.html` template is inheriting from the query template. 

And is there also a Gutenberg bug referenced here too?

**Comment by jffng** [comment]
> Yes, we need an archive page template that includes the Archive Title at the top.

We will need https://github.com/WordPress/gutenberg/pull/33515 to do this.

**Comment by jffng** [comment]
> Yes, we need an archive page template that includes the Archive Title at the top.

I think we will need https://github.com/WordPress/gutenberg/pull/33515 to do this.

**Comment by jffng** [comment]
> is there also a Gutenberg bug referenced here too?

I believe this is related https://github.com/WordPress/gutenberg/issues/35322. 

When I add `"inherit":true` to the index query, sticky posts do not display first, even though the query is set to include them. I am not sure if this is the correct behavior.

**Comment by kjellr** [comment]
Oh weird — that does sound wrong.

**Comment by carolinan** [comment]
Closing this in favor of the upstream issue. 
I still think the query on the index should have the inherit enabled, but that does not solve the new issues we found.

The problem with sticky posts showing on top every page can actually be reproduced in a classic theme without Gutenberg installed, meaning it is not a new issue.
