### ISSUE TITLE
Update Gutenberg to use 2022

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentytwo#133]
**Description**
It would be helpful to get more folks working on Gutenberg to start testing with 2022. Some ideas that could help with that:

- [x] Tag releases (similar to [this](https://github.com/WordPress/theme-experiments/issues/195)) prior to the theme's inclusion in core, so Gutenberg can pin its testing dependency on a specific version of the theme.
- [ ] Replace `tt1-blocks` with `twentytwentytwo` in the `.wp-env.json` [config](https://github.com/WordPress/gutenberg/blob/trunk/.wp-env.json#L4)

Other thoughts or ideas?

**Comment by colorful-tones** [comment]
These seems like a great idea, and I feel like it would help with testing. I love the idea of releases, as it also affords the ability for user to download a .zip. In case their not as technically inclined or interested in spinning up a unique site/codebase, etc.

**Comment by jffng** [comment]
Closing this since the theme is in core trunk now.
