### ISSUE TITLE
Images show wrong aspect ratio in the frontend

### ISSUE THREAD

**Issue by mtoensing** [WordPress/twentytwentytwo#138]
**Describe the bug**
Fresh WordPress installation shows uploaded images with a stretched aspect ratio. Happens to all uploaded images. Switching to twenty-twenty-one or twenty-twenty renders them just fine. Happens to already uploaded images and new ones. 

**To Reproduce**

1. Upload an image. 
2. Look at post in frontend

**Expected behavior**
All images should keep their aspect ratio.

**Screenshots**
![gutenberg-2022](https://user-images.githubusercontent.com/136737/138082454-9db63a76-860b-4729-95ad-7f43a2fc8be3.png)
![frontend-2022](https://user-images.githubusercontent.com/136737/138082460-639050bf-13bf-4477-9380-96abdcbbf976.png)

**Device inphone:**
MacOS, Chrome

**Comment by jffng** [comment]
Hi @mtoensing thanks for the report. What version of Gutenberg are you using? 

I believe this was resolved upstream in https://github.com/WordPress/gutenberg/pull/30092, as I don't see a `height: auto;`. This fix will be shipped with version 11.8 of the plugin I believe, so unless you're running Gutenberg trunk I believe we can close the issue.

**Comment by mtoensing** [comment]
Thanks!

**Comment by mtoensing** [comment]
Had to install this: https://github.com/bph/gutenberg/releases/tag/11.9.-nightly
