### ISSUE TITLE
Post content does not have padding in the editor

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentytwo#144]
**Describe the bug**

Currently because of where our padding is applied, post content does not appear with padding in the editor.

**To Reproduce**

1. Go to the post editor
2. Add some content
3. Preview on mobile

**Expected behavior**
I expect the padding to mirror what's displayed on the front-end.

**Screenshots**
Editor | Front-end
-------- | -------
<img width="1258" alt="Screen Shot 2021-10-21 at 2 43 15 PM" src="https://user-images.githubusercontent.com/5375500/138338006-01e302ed-a635-4ded-946c-e5e1cbd0fb45.png"> | <img width="419" alt="Screen Shot 2021-10-21 at 2 43 49 PM" src="https://user-images.githubusercontent.com/5375500/138338027-69cc7e2e-1a29-4b5d-ab19-b0f94ad1eab1.png">

**Additional context**
This is happening because in our templates, we apply padding to a group block that contains the post-content, not the post-content itself or any children of it: https://github.com/WordPress/twentytwentytwo/blob/trunk/block-templates/single.html#L3 

The editor only renders the post-content, which has no padding. It isn't aware of the container that has the padding applied, which I think is the correct behavior.

**Comment by kjellr** [comment]
Closing to consolidate this issue into https://github.com/WordPress/twentytwentytwo/issues/234.
