### ISSUE TITLE
Determine strategy for templates that use sidebars

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#151]
A couple of the theme mockups feature a simple sidebar on the left or right: 

Left Sidebar|Right Sidebar
---|---
<img width="1200" alt="Blog" src="https://user-images.githubusercontent.com/1202812/138500019-d25ad7a7-2633-4e06-8661-02cbb54af72e.png">|<img width="1200" alt="Blog-1" src="https://user-images.githubusercontent.com/1202812/138500017-280597a9-fd03-4878-8558-a0e2888ddff1.png">

I think it's worthwhile to making these templates available, but I'm not certain the best way to implement them within the boundaries of what will launch with 5.9. Ideally, users would be able to switch out their entire `index.html`, `single.html`, and `page.html` templates for versions of these. But FSE doesn't currently include the concept of swapping out entire templates except on a single post/page basis. 

I _think_ this seems like the best route for now:

- Offer a few alternate page templates that map to these mockups. For example:
    -  "Left sidebar: Post list"
    -  "Left sidebar: Single post"
    -  "Left sidebar: Single page"
- We'd also bundle a "sidebar" template part so that would stay in sync across these templates. 
- Users could then assign one of those templates to static pages as needed. 

It's not totally ideal, but I think it would technically work? The other option is basically to just build these as patterns and folks can paste them into the post/page content using our "Blank" page template. 

I'm curious if other folks have ideas!

**Comment by overclokk** [comment]
Personally what I think is less it's better, because there are more combination with content and sidebar, here a few;

```
sidebar-sidebar-content
sidebar-content-sidebar
content-sidebar-sidebar

sidebar-content
content-sidebar

content
```

I'm experimenting a theme with only `singular.html` for page and post with only the `content` and adding a pattern with `content-sidebar`, so you can add the template you need only if you need it, switching sidebar left to right is a matter of a click on the arrow button.

**Comment by carolinan** [comment]
> I think it would technically work? The other option is basically to just build these as patterns and folks can paste them into the post/page content using our "Blank" page template.
> 
> I'm curious if other folks have ideas!

Yes using template parts for it works.
A pattern also works well when users do not want to use the same sidebar content.
