### ISSUE TITLE
Post Categories and Post Tags blocks not working

### ISSUE THREAD

**Issue by alberto-marin** [WordPress/twentytwentytwo#152]
**Describe the bug**
When adding Post Categories or Post Tags blocks to a page it won't load any content, regardless the Post Categories or Post Tags have posts assigned to a post or not.

**To Reproduce**
1. Go to 'Pages -> Sample Page -> Edit Page '
2. Click on 'Block Inserter -> Add Post Categories or Post Tags block'
3. A spinner will appear all the time
4. No error will display, but nothing will come up

**Expected behavior**
When I add a block for Post Categories or Post tags I'm expecting to see either a list of Post Categories or Tags, or a warning message with some information explaining why it's not displaying any information.

**Screenshots**
![Screenshot 2021-10-22 at 19 54 00](https://user-images.githubusercontent.com/10046225/138508361-a9599ec2-c402-4443-978a-0ad6d0720166.png)
![Screenshot 2021-10-22 at 19 54 12](https://user-images.githubusercontent.com/10046225/138508371-3a718c30-4d77-4bdc-a740-9f608bda8235.png)

**Device inphone:**
 - Device: MacBook Pro (13-inch, M1, 2020)
 - OS: OS X 10.15.7
 - Browser: Chrome
 - Version: 95

**Comment by carolinan** [comment]
Hi!
The upstream issue for this is https://github.com/WordPress/gutenberg/issues/34212

**Comment by kjellr** [comment]
Thank you both! Since this is not specifically a theme issue, I'm going to close for now.
