### ISSUE TITLE
Font size slug naming best practice

### ISSUE THREAD

**Issue by ellenbauer** [WordPress/twentytwentytwo#153]
**Is your feature request related to a problem? Please describe.**

I know this has been discussed before but I wanted to bring it up as a discussion here, since I still wonder if the currently used approach for font size slugs is really the best practice that will/should be established. 

I would just love to hear your feedback and thoughts that went into the decision for naming being small, normal, medium, large, huge, gigantic(?).

**Describe the solution you'd like**
From my perspective this naming pattern does not seem not 100% intuitive nor is it easily scalable. My suggestion would be to use a system like it is common in system like Tailwind uses: xs, s, base or m, l, xl, xxl, 3xl and so on: https://tailwindcss.com/docs/font-size

This would make it easier to scale the system if needed, the naming system it's commonly understood and it would result in shorter slugs as well.

In regards to the suggestion that all themes in the directory should preferably use the same font size slugs it also seems to be an easier to follow solution in my opinion.

**Comment by Riyadh1734** [comment]
Thanks for your kind suggestions. Yes, the same font size slugs help a lot to be easier to the solutions.

**Comment by overclokk** [comment]
There is also a discussion on gutenberg repo about this https://github.com/WordPress/gutenberg/issues/29568
I think this should be discussed befor 5.9

**Comment by carolinan** [comment]
The font sizes from WordPress core are always output even if the themes do not use them.
So if you switch to s, m, xxxxl and so on, you will still have:
small, medium, normal, large.
Even if the WordPress default font size names/slugs are changed in 5.9, there will still be backwards compatibility issues (for those that want or need their themes to be backwards compatible).

That is why, unless the above is solved, I think it is still best to add new values to existing slugs.

**Comment by kjellr** [comment]
Thanks for the issue, @ellenbauer! 

I agree that we're in need of a more scalable system here. But as @carolinan noted, we're following Gutenberg's lead for the font size names + slugs at the moment. If there's movement on that end, we can reconsider for the theme, but in the meantime I think it makes sense to close this issue. We can re-open if needed later on! 

(Related: https://github.com/WordPress/twentytwentytwo/issues/37#issuecomment-937784053)
