### ISSUE TITLE
Featured image cannot be inserted

### ISSUE THREAD

**Issue by elbsegler63** [WordPress/twentytwentytwo#155]
If I want to write a new post and I use the "single post" template, I cannot insert a featured image, even though the template provides for a featured image. This entry is missing in the right sidebar, right?

![kein-menue-fuer-beitragsbild](https://user-images.githubusercontent.com/85250773/138547250-148b1435-2472-4469-9bed-53fe7d9b01ff.PNG)
![listen-darstellung-single-post](https://user-images.githubusercontent.com/85250773/138547373-7628d283-fe5e-488f-a0c5-2771d968da04.PNG)

**Comment by LittleBigThing** [comment]
I think that theme support is coming out-of-the-box, the [pull request](https://github.com/WordPress/gutenberg/pull/35593) has just been merged in the editor.

**Comment by elbsegler63** [comment]
Thank you for the information. Then I'll wait until the time comes.
