### ISSUE TITLE
Opt the theme into font smoothing for better font rendering

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#161]
This may require a bit of CSS, unless https://github.com/WordPress/gutenberg/issues/35934 ends up happening. 

```
-moz-osx-font-smoothing: grayscale;
-webkit-font-smoothing: antialiased;
```

**Comment by kjellr** [comment]
Here's a before/after comparison:

_Without font smoothing_

<img width="1056" alt="Screen Shot 2021-10-25 at 3 45 36 PM" src="https://user-images.githubusercontent.com/1202812/138760318-d481edcd-7660-4b57-b75b-7e379c91a942.png">

_With font smoothing_

<img width="1082" alt="Screen Shot 2021-10-25 at 3 45 53 PM" src="https://user-images.githubusercontent.com/1202812/138760330-77356898-649a-420b-a385-a4feab07802f.png">

**Comment by bgardner** [comment]
As I mentioned [here](https://github.com/WordPress/gutenberg/issues/35934#issuecomment-954784889), I am a huge advocate of font-smoothing. Especially for TT2, since it’s absence is the first thing I notice every time I view the demo or test it locally.

**Comment by sagarnasit** [comment]
Based on [this discussion](https://github.com/WordPress/gutenberg/pull/36092#issuecomment-957401611) font smoothing is supposed to be added via theme style rather than theme.json.

Let me know if I can help with that.
