### ISSUE TITLE
Reconsider use of Site Tagline for the large header on the homepage

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#170]
Currently, the large header area on the homepage uses the Site Tagline block: 

<img width="1231" alt="Screen Shot 2021-10-28 at 9 03 55 AM" src="https://user-images.githubusercontent.com/1202812/139261026-a856660f-813b-4249-ad78-63d2f239473e.png">

I've been going back and forth about whether this is a good idea, so I thought I'd write down my concerns. the alternative is just to have it be a heading block. 

Pro:
- It's pre-populated with something that's potentially relevant on theme switch.
- If users are confused about how to customize it, there's a second place they can edit it: `Settings > Reading`. (However, once there's [a bird image](https://github.com/WordPress/twentytwentytwo/issues/92) in there, folks will learn to edit the template part in order to remove/change that image anyway.)

Con:
- It's a little unexpected — usually the site tagline is nowhere near this prominent. 
- Users might want their site tagline (as used for SEO and in the title tag) to be different than the big message they use to greet visitors.
- Semantically, it's a paragraph, but visually it seems more like a headline. 
- The site tagline does not support rich text controls, so we can't actually achieve [the italicized part of the original mockup](https://cloudup.com/cQMwENCI3KO).
- Once we have the bird image in there, I think "Just another WordPress site" is going to be a really weird text pair for it. Plus, it wraps oddly. 😕 

I'm interested in other folks' thoughts!

**Comment by jffng** [comment]
Hmm, I think it makes more sense for this to be a heading, as the text here seems to be specific to the homepage, whereas the tagline would be more general (something that you could display on every page, rather than a "greeting").

**Comment by jffng** [comment]
Not directly related, but the font family declaration is not working for the site tagline. Below is a screenshot, I added a heading block above it to show that font family is being loaded, just not applied correctly to the site tagline: 

<img width="854" alt="Screen Shot 2021-10-28 at 9 48 07 AM" src="https://user-images.githubusercontent.com/5375500/139269508-f29dada8-6809-4136-b94e-f16c6fb95e83.png">

Should we open a separate issue to track, or can we tackle it with this one?

**Comment by kjellr** [comment]
Might as well just tackle it here.
