### ISSUE TITLE
Add theme description

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#171]
The theme needs a theme description in its `readme.txt`, and under the Description field in `style.css`. Currently it just uses a temporary "The WordPress default theme for 2022" message.

For example, here are the theme descriptions for the previous two default themes: 

**Twenty Twenty-One**

> Twenty Twenty-One is a blank canvas for your ideas and it makes the block editor your best brush.
> 
> With new block patterns, which allow you to create a beautiful layout in a matter of seconds, this theme’s soft colors and eye-catching — yet timeless — design will let your work shine.
> 
> Take it for a spin! See how Twenty Twenty-One elevates your portfolio, business website, or personal blog.

**Twenty Twenty**

> Our default theme for 2020 is designed to take full advantage of the
flexibility of the block editor. Organizations and businesses have the
ability to create dynamic landing pages with endless layouts using the
group and column blocks. The centered content column and fine-tuned
typography also makes it perfect for traditional blogs. Complete editor
styles give you a good idea of what your content will look like, even
before you publish. You can give your site a personal touch by changing
the background colors and the accent color in the Customizer. The colors of
all elements on your site are automatically calculated based on the colors
you pick, ensuring a high, accessible color contrast for your visitors.

**Comment by mburridge** [comment]
How about this? Happy to receive feedback on content, wording, tone, etc... and suggestions for improvement before creating a PR.


> Built with a “full site editing first” mindset, Twenty Twenty-Two has been designed to be the most flexible default theme ever created for WordPress. 
>
> Lightweight, and featuring subtle design choices inspired by nature, the theme is nevertheless built with a solid foundation and is as robust and reliable as it is beautiful.
>
> Everyone wants their website to be unique and so Twenty Twenty-Two is endlessly customisable. It takes full advantage of the power of full site editing with templates and template parts that can be easily over-ridden in the site editor. Additionally the theme features a variety of alternative colour schemes to set just the right mood and give any site an appearance that shows off the content in the best possible light.


_Inspiration taken from the [introduction post](https://make.wordpress.org/core/2021/10/06/introducing-twenty-twenty-two/)_

**Comment by kjellr** [comment]
Thanks @mburridge! This is a good start! I have some slight ideas for refinement, and will dive into it next week.

**Comment by kjellr** [comment]
I spent a bit of time iterating on the description this morning, and here's where I've ended up: 

> Twenty Twenty-Two is designed to embrace the idea that everyone deserves a truly unique website, formed on a solidly-designed foundation. 
> 
> The theme’s foundational styles are inspired by the diversity and versatility of birds. Its typography is lightweight yet strong, its color palette is drawn from nature, and its layout elements sit gently on the page. The theme includes dozens of block patterns, opening the door to a wide range of beautifully-designed layouts in just a few clicks. 
> 
> The true richness of Twenty Twenty-Two lies in its opportunity for customization. The theme is built to take advantage of the Full Site Editing features built into WordPress 5.9. This means that colors, typography, and the layout of every single page can be customized to suit your vision. 
> 
> Whether you’re building a single-page website, a blog, a marketing site, or a portfolio, Twenty Twenty-Two is designed to help you create a site that is uniquely yours. 

As you'll no doubt notice, this is significantly influenced by [the announcement post](https://make.wordpress.org/core/2021/10/06/introducing-twenty-twenty-two/). I could use some suggestions for refinement. Namely: 

- I'd like to flip that first sentence so that it cites the "foundation" first, and then the unique website bit. That would mirror the order of the subsequent paragraphs.
- I'm unsure about including the "block patterns" sentence in the "foundation" paragraph. The other two sentences there are more aesthetic/conceptual, so it feels weird to end with a tactical description. 
- This might benefit from being a sentence or two shorter.

Open to other thoughts and suggestions as well!

**Comment by clucasrowlands** [comment]
Hey @kjellr! Here's a suggested edit, based on what you have (and considering your comments). Feel free to tweak it further, or let me know if you have other questions.

> Built on a solidly designed foundation, Twenty Twenty-Two embraces the idea that everyone deserves a truly unique website. The theme’s foundational styles are inspired by the diversity and versatility of birds: its typography is lightweight yet strong, its color palette is drawn from nature, and its layout elements sit gently on the page. 
> 
> The true richness of Twenty Twenty-Two lies in its opportunity for customization. The theme is built to take advantage of the Full Site Editing features built into WordPress 5.9, which means that colors, typography, and the layout of every single page on your site can be customized to suit your vision. It also includes dozens of block patterns, opening the door to a wide range of professionally designed layouts in just a few clicks.
> 
> Whether you’re building a single-page website, a blog, a business website, or a portfolio, Twenty Twenty-Two will help you create a site that is uniquely yours.

***

You could also consider "core styles" instead of "foundational styles" in that second sentence if you feel "foundation" and "foundational" are too close together.

**Comment by kjellr** [comment]
Thank you @clucasrowlands! This looks great. 

> You could also consider "core styles" instead of "foundational styles" in that second sentence if you feel "foundation" and "foundational" are too close together.

I think we can actually just say "styles" here without "core" or "foundational", and it will work just fine. 

I'll open a PR to make this change!
