### ISSUE TITLE
Consider new block patterns

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#172]
We added the originally designed block patterns already, but I'd like to leave open the door for some more. This issue will serve a place to track that work. 

I'd specifically like to add more of the poster-like "Page" patterns, since we only have a few of those:

![136080878-6bbad782-dbd1-4f11-bc59-6ac361e49fd2](https://user-images.githubusercontent.com/1202812/139277615-fd4bbe3e-92f1-4271-ad6d-88422c07ee30.png)

**Comment by beafialho** [comment]
Here are a few suggestions. I tried a couple different background colors and took the liberty of adding some names/content.

![Page Layout-1](https://user-images.githubusercontent.com/65220155/139283808-fcb4a45f-2485-4734-8387-44dc22bc9774.jpg)

![Page Layout-2](https://user-images.githubusercontent.com/65220155/139283824-498dd3ba-6f8a-44e4-ae5d-9ce70d4e8474.jpg)

![Page Layout-3](https://user-images.githubusercontent.com/65220155/139283839-877ee39a-6d57-4ed2-95f5-06bd1387f497.jpg)

![Page Layout-4](https://user-images.githubusercontent.com/65220155/139283842-29909a10-130b-49fe-87d9-e2624403b37c.jpg)

![Page Layout](https://user-images.githubusercontent.com/65220155/139283845-38040301-375b-419f-a999-a10dcdc2da33.jpg)

**Comment by kjellr** [comment]
Cool, thanks @beafialho! I'll try building a few of these out to see how they work. 👍

**Comment by kjellr** [comment]
Just a quick update: 

- I began building [that first one](https://user-images.githubusercontent.com/65220155/139283808-fcb4a45f-2485-4734-8387-44dc22bc9774.jpg), but had a hard time getting the image resized down to something reasonable. Will give it another try tomorrow. 
- The [next](https://user-images.githubusercontent.com/65220155/139283824-498dd3ba-6f8a-44e4-ae5d-9ce70d4e8474.jpg) [two](https://user-images.githubusercontent.com/65220155/139283839-877ee39a-6d57-4ed2-95f5-06bd1387f497.jpg) might be a bit problematic because the editor currently lacks support for changing the font family for paragraph blocks. In both of those patterns, the names are in Source Serif, but they are content, not headings. I'm not quite sure of a great way around this yet, but I may end up filing a Gutenberg issue or two in the meantime.

**Comment by kjellr** [comment]
A couple other ideas: 

- We had to cut the right-sidebar pattern from #164. It didn't work with the content as designed, but I think we could easily design a pattern that does. It would be great to have a right-sidebar pattern represented in the set. 
- Our header patterns are overwhelmingly white and similar. I'd like to try varying those a little bit more.

**Comment by beafialho** [comment]
> The next two might be a bit problematic because the editor currently lacks support for changing the font family for paragraph blocks. In both of those patterns, the names are in Source Serif, but they are content, not headings. I'm not quite sure of a great way around this yet, but I may end up filing a Gutenberg issue or two in the meantime.

I see. I can also try to redesign these using the paragraph font.

> Our header patterns are overwhelmingly white and similar. I'd like to try varying those a little bit more.

Working on some colourful header patterns at the moment, will post them here soon.

**Comment by beafialho** [comment]
For headers, here are some suggestions with color.

<img width="1200" alt="Header-7" src="https://user-images.githubusercontent.com/65220155/140089654-cd07fa83-1b5b-40c4-b57f-64a744b126aa.png">
<img width="1200" alt="Header-5" src="https://user-images.githubusercontent.com/65220155/140089658-4229de18-4a23-4ffe-abb4-d7e97dda6327.png">
<img width="1200" alt="Header-4" src="https://user-images.githubusercontent.com/65220155/140089659-622271f7-ebb4-4abe-89fb-46528a11820b.png">
<img width="1200" alt="Header-3" src="https://user-images.githubusercontent.com/65220155/140089660-68610874-4f9a-43eb-be40-0e4ae7e49ab5.png">
<img width="1200" alt="Header" src="https://user-images.githubusercontent.com/65220155/140089662-1674bc6d-6732-4e84-a628-01ae33357fb2.png">

And a few using images in the header's backgrounds, as suggested in #184.

<img width="1200" alt="Header-1" src="https://user-images.githubusercontent.com/65220155/140089475-5ca6ae25-9465-4291-a266-72bd11804373.png">
<img width="1200" alt="Header-6" src="https://user-images.githubusercontent.com/65220155/140089484-0ad7048a-f447-409f-8497-193bbb13e001.png">
<img width="1200" alt="Header-2" src="https://user-images.githubusercontent.com/65220155/140089553-e438c7d8-74a0-45cd-9f17-9baf206e9b06.png">

I also redid the two patterns that weren't viable to achieve with Source Serif, they seem to work pretty well with the paragraphs font.

![Page Layout-1](https://user-images.githubusercontent.com/65220155/140091315-151988ff-612c-4b35-8ace-d720b8aebfe7.jpg)
![Page Layout](https://user-images.githubusercontent.com/65220155/140091294-b0b77d4c-190f-4a0c-a266-429ddb3886fc.jpg)

**Comment by kjellr** [comment]
🎉 These are wonderful, thanks @beafialho. I'll try building these later this week.

**Comment by carolinan** [comment]
The green header with background image looks amazing.

The header with the bird image might be tricky, I tried something similar but depending on screen width and number of menu items, the menu text overlaps the graphics in a way that makes the text difficult to read.

**Comment by beafialho** [comment]
Definitely @carolinan, I was hesitant with that one too. It's probably more prudent to keep more abstract images in the header. If there's a more opaque overlay, it could work:

![Mobile](https://user-images.githubusercontent.com/65220155/140309374-59b0800c-91f3-4525-99ae-89e3ffeaeec4.png)

**Comment by kjellr** [comment]
I think it's worth including anyway. If necessary, we can suggest an ideal number of menu items for the header, just like we do for this one: 

<img width="582" alt="Screen Shot 2021-11-04 at 7 56 35 AM" src="https://user-images.githubusercontent.com/1202812/140309513-ce43a622-99f4-4b6a-87c3-75631c7cd24b.png">

I'll try build these today, as additions to https://github.com/WordPress/twentytwentytwo/pull/204.
