### ISSUE TITLE
Position blocks below the post and above the comment

### ISSUE THREAD

**Issue by mtoensing** [WordPress/twentytwentytwo#178]
**Is your feature request related to a problem? Please describe.**
Blocks like related articles and recent posts are usually appended as blocks to the content. 

**Describe the solution you'd like**
A better position would be below post meta (tags, author) and above the comment section.

![Screen Shot 2021-10-29 at 09 52 45](https://user-images.githubusercontent.com/136737/139397284-63d457a9-56ee-498a-8500-3bd447477a5c.png)

**Comment by kjellr** [comment]
Hey @mtoensing — I'm not sure the theme can specifically decide where 3rd party plugins place content like that. If those plugins supply these features as blocks, you should be able to position them wherever you'd like in the template editor. 

Can you share a more specific example of what you're seeing?

**Comment by mtoensing** [comment]
@kjellr  

Sorry, I misunderstood the single post template in FSE. When I selected a post and started FSE by choosing "edit site" I always ended up on the index template. Now I see that I can add a block between these blocks. Evrything is a block. Great. Solved.
