### ISSUE TITLE
Replace "Post Comments" block with the Comments Query Loop block in templates

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#179]
Post Comments will remain [marked as "experimental" for 5.9](https://github.com/WordPress/gutenberg/pull/35979#issuecomment-954364262). We should replace with the new "Comments Query Loop" block from https://github.com/WordPress/gutenberg/pull/35231.

**Comment by scruffian** [comment]
I made a start on this here: https://github.com/WordPress/twentytwentytwo/pull/192

**Comment by jffng** [comment]
Closing because Post Comments will be available in 5.9, Comments Query Loop is still in early stages.
