### ISSUE TITLE
Provide a header pattern that uses a background image

### ISSUE THREAD

**Issue by lwangdu** [WordPress/twentytwentytwo#184]
**Is your feature request related to a problem? Please describe.**
Currently  the full site editor you can color background color header template but there is no way you can add image background on the header template from the dashboard.

**Describe the solution you'd like**
If user can add image background color or background image option that would be great.  Here is an example of screen shot that I am talking about it.
![Screen Shot 2021-10-29 at 3 42 25 PM](https://user-images.githubusercontent.com/24829573/139509228-a6933c10-c8ab-4b48-ab6f-f07f245f0fc3.png)

**Comment by carolinan** [comment]
With full site editing background images are added using the cover block. So you need to add the right block.

**Comment by lwangdu** [comment]
Thanks @carolinan I was able to add the cover block on the header template area but. There is no option to set full width cover block.
![Screen Shot 2021-10-31 at 12 01 25 PM](https://user-images.githubusercontent.com/24829573/139597751-6e3704c4-bb01-4c45-85d4-d26595531879.png)
as you can see my screen short

**Comment by carolinan** [comment]
That is full width? I mean it looks like it stretches the whole content area. The grey border is always there, it is part of the editor.

**Comment by carolinan** [comment]
If the width options are missing you may need to place it inside a container block like a group or template part.

**Comment by kjellr** [comment]
That's right — the gray there is part of the site UI. That said, I think it would be worthwhile to bundle block pattern that includes an image in the header to make this a little easier. I'll keep this issue open, but reframe it for that purpose.

**Comment by lwangdu** [comment]
Great would be wonderful thank you for your great!

**Comment by sagarnasit** [comment]
@kjellr @carolinan Let me know if I can help with the contribution here.

**Comment by carolinan** [comment]
I played around with the existing image assets as cover blocks, with the logo/site title and both standard and "button only" navigation blocks but it did not feel right. Needs a designer =D
