### ISSUE TITLE
Use TGMPA to inform that the Gutenberg plugin is required

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwentytwo#188]
**Is your feature request related to a problem? Please describe.**

Trying to activate the Twenty Twenty-Two theme while the Gutenberg plugin is not installed, leads to the following error message:

<img width="814" alt="Screen Shot 2021-10-30 at 15 40 34" src="https://user-images.githubusercontent.com/3323310/139526304-1c53bd07-4ef0-40c3-a6ae-270b4a6ac332.png">

**Describe the solution you'd like**

Instead of showing an error message to the user, I suggest using [TGM Plugin Activation](https://github.com/TGMPA/TGM-Plugin-Activation) to not only inform a user about the required plugin, but also offer an easy installation. I believe such a change leads to a better onboarding experience.

**Comment by colorful-tones** [comment]
This error message will not happen when this theme is part of its targeted WordPress 5.9 proper release. 

Also, this theme's `README.md` clearly states under the Getting Started:

> 2. Install the [Gutenberg plugin](https://wordpress.org/plugins/gutenberg/).

**Comment by nielslange** [comment]
Thanks for pointing this out, @colorful-tones! 🙌
