### ISSUE TITLE
Cannot replace a header in tempates

### ISSUE THREAD

**Issue by elbsegler63** [WordPress/twentytwentytwo#189]
**Describe the bug**
I want to replace a header with another header in a template. The change is not saved.

**To Reproduce**
1. Go to Appearance -> Templates -> Single Post (No Seperators) an edit.
2. Click on 'Replace' the header, choose another one
3. Save 
4. Open them Template again, the old header is part of the template.

**Expected behavior**
The chosen header in the template

**Screenshots**
![grafik](https://user-images.githubusercontent.com/85250773/139586373-a9dba307-e486-48b5-a1ed-b48a82d68866.png)

**Device inphone:**
 - Device: Desktop
 - OS: W10
 - Browser: Firefox
 - Gutenberg: 11.8.00
 - Twenty Twenty-Two: 0.1
 - WP: 5.9-alpha-51958

**Comment by elbsegler63** [comment]
This issue certainly belongs to # 123 here. Should I close the issue? 

I am not sure. Because I expected that I would get to my destination on the path I described and that I would be able to replace the header. Apparently you can save, but without success.

**Comment by carolinan** [comment]
This has been solved in Gutenberg 🎉 and the fix will be in 11.9 / 5.9.
