### ISSUE TITLE
Better organize the code in functions.php

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#191]
There's not actually much code in functions.php, but it is very dense. We should clean this up to so that it's easier to read with some extra space and file/function headers. 

Here's our functions.php vs. the one for Twenty Twenty-One for example:

Twenty Twenty-Two|Twenty Twenty-One
---|---
<img width="1138" alt="Screen Shot 2021-11-01 at 12 33 32 PM" src="https://user-images.githubusercontent.com/1202812/139706947-c1cdd2aa-2308-4867-9546-74edd4637322.png">|<img width="1111" alt="Screen Shot 2021-11-01 at 12 33 43 PM" src="https://user-images.githubusercontent.com/1202812/139706950-6f991037-56e6-41bd-8770-191bea56e98b.png">

**Comment by mburridge** [comment]
I can take this if you want to assign it to me.

**Comment by kjellr** [comment]
Thanks @mburridge, go for it!

**Comment by jffng** [comment]
Closed by #195.
