### ISSUE TITLE
Add schema support for theme.json

### ISSUE THREAD

**Issue by dgwyer** [WordPress/twentytwentytwo#194]
Adding schema support for `theme.json` as described [here](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#developing-with-theme-json) enables automatic validation and auto-complete in supported editors.

Just needs this line adding above `"version"`:

`"$schema": "https://json.schemastore.org/theme-v1.json"`

**Comment by Soean** [comment]
> Note that this syntax is VS Code-specific and not part of the JSON Schema specification.
Source: https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json

JetBrains IDEs like IntelliJ IDEA, PhpStorm or WebStorm work with it out of the box without this line. I am not sure if we should add this line for one specific editor.

**Comment by dgwyer** [comment]
The docs indicate that this will work in other editors, not just VS Code:

> To use the schema, add "$schema": "https://json.schemastore.org/theme-v1.json" to the beginning of your theme.json file. Visual Studio Code **and other editors** will pick up the schema...

Is this not the case?

Also, not sure what you meant by:

> JetBrains IDEs like IntelliJ IDEA, PhpStorm or WebStorm work with it out of the box without this line.

How do these editors use the schema out of the box?

**Comment by scrobbleme** [comment]
> > JetBrains IDEs like IntelliJ IDEA, PhpStorm or WebStorm work with it out of the box without this line.
> 
> How do these editors use the schema out of the box?

For Jetbrains IDEs there is a WordPress plugin available. If you use this, they *might* be able to recognize it automagically...

**Comment by Soean** [comment]
The JetBrains IDEs use the filename and search for it on [schemastore.org](https://www.schemastore.org/json/) (which links to the [Gutenberg GitHub Repo](https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/theme.json)), see https://www.jetbrains.com/help/idea/json.html#ws_json_using_schemas

**Comment by scrobbleme** [comment]
@Soean Thanks, but is this really working. I'm using JetBrains since year and never had automatic JSON support...
 
 Just checked, and had to manually select the theme for a theme.json

**Comment by Soean** [comment]
Its working in IntelliJ for me and my colleges, sometimes you first have to enable it in your settings or update the schemas.

**Comment by scrobbleme** [comment]
Awesome, thanks. 
I've reset the schema configuration and it seems to work now...  maybe it was just broken, as I basically use the same settings since a decade or so for now and just always upgraded IntellIJ ;)
