### ISSUE TITLE
Add support for borders in theme.json

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentytwo#198]
**Is your feature request related to a problem? Please describe.**
Unlike most block themes available on the WordPress.org repository, Twenty Twenty-Two doesn’t add support for borders in the settings section of the theme.json file. Is it on purpose? It can be weird for users who have created their site using another block theme and want to switch to Twenty Twenty-Two as they can’t edit the block border previously added with the other theme.

**Describe the solution you'd like**
Add support for borders.

**Comment by kjellr** [comment]
This is not intentional, and I think it makes sense to add it. This would make a `Good first issue`, so I'm adding that label.  Just missing the following from the `settings` section of theme.json: 

```
"border": {
	"customColor": true,
	"customRadius": true,
	"customStyle": true,
	"customWidth": true
},
```
