### ISSUE TITLE
Set up 2022.wordpress.net

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentytwo#21]
We should set up a development site + a github action that deploys `trunk` of this theme. This is probably separate from 2022.wordpress.net?

**Comment by kraftbj** [comment]
It could be 2022.wordpress.net. The action would need to push up via SFTP/SSH and we'd need to create a key for it. Previous sites, I manually updated it ~weekly during dev.

Happy to own this one.

**Comment by kjellr** [comment]
Thanks, @kraftbj!

**Comment by pbking** [comment]
@kraftbj I opened #94 for an alternate "workshop" location where we can have an uh... less appealing and more edge-casey site than 2022.wordpress.net while we bang out some kinks.  

Perhaps that action could be augmented to also include 2022.wordpress.net for a location with cleaner content?

**Comment by kraftbj** [comment]
I like that idea @pbking. Either augment or have a second one that does the same thing. I've requested the site and asking the Systems folks if they prefer a SSH keypair or user/pass for a dedicated SFTP user for this purpose. Thank you!

**Comment by kraftbj** [comment]
@kjellr I've setup an admin user for you on the site. You can password recover with your automattic e-mail address (check spam; the wordpress.net servers aren't well-liked).

I've setup Akismet and added a comped account. Comments are all moderated, anyhow, but no need to keep spam around.

**Comment by kjellr** [comment]
Thanks for the help, @kraftbj! I'll keep this issue open while I populate it with demo content later today, but I'll reassign it to myself.
