### ISSUE TITLE
Switch theme.json to v2 (remove "custom" prefix)

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentytwo#210]
While version 1 will still work in 5.9, I think the theme should use version 2:
https://github.com/WordPress/gutenberg/pull/36155

Do we also need to wait for https://github.com/SchemaStore/schemastore/pull/1907?

**Comment by carolinan** [comment]
@ajlende is this the correct way to add the schema back?
`"$schema": "https://schemas.wp.org/trunk/theme.json",`
Does it now support version 2 of theme.json?

(I needed to remove it here: https://github.com/WordPress/twentytwentytwo/pull/217/files#diff-160c735a986cf8c05e1f6b2e9ac89dd0410562d2fe5ccbdc93157bd92f3dc2bcL2)

**Comment by ajlende** [comment]
That is correct for Visual Studio Code for the latest version. The latest version, however, had a bug where the version was not updated with the changed properties, so I added a fix here https://github.com/WordPress/gutenberg/pull/36917
