### ISSUE TITLE
Try replacing navigation page list with named navigation areas

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentytwo#212]
The theme could take advantage of the new navigation area block and at the same time, increase the usage and testing of the new block:
https://github.com/WordPress/gutenberg/pull/36178

**Comment by kjellr** [comment]
How does this work if there _are_ no navigation areas defined? Will the menu appear empty?

**Comment by carolinan** [comment]
It is empty on the front if there is no menu previously assigned to the area.

This works in the editor and for using existing menus.
```
<!-- wp:navigation-area {"area":"primary"} -->
<!-- wp:navigation {"itemsJustification":"right","isResponsive":true} /-->
<!-- /wp:navigation-area -->
```

But with the following code, the page list shows on the front.
In the editor, the page list is showing in the _list view_ but is not used by the navigation block 🤔. Clicking the navigation block shows that it is empty:
```
<!-- wp:navigation-area {"area":"primary"} -->
<!-- wp:navigation {"itemsJustification":"right","isResponsive":true} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->
<!-- /wp:navigation-area -->

```

**Comment by carolinan** [comment]
But we also need this area populated for when people switch *from* Twenty Twenty-Two 🤔 so that their menus show in the correct location.

**Comment by carolinan** [comment]
https://github.com/WordPress/gutenberg/issues/36306

**Comment by carolinan** [comment]
I propose closing this, as navigation areas are being reverted:
https://github.com/WordPress/gutenberg/pull/36604/files

**Comment by kjellr** [comment]
That makes sense. I'll close for now, and we can reopen if something changes.
