### ISSUE TITLE
Consider adding a print style

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentytwo#214]
Consider adding a print CSS file to hide clutter on printed pages.

**Comment by kjellr** [comment]
We can leave this open for now, but in keeping with our "lightweight, as little CSS as possible" approach, my guess is that we won't add in a separate print stylesheet for the theme.

**Comment by kjellr** [comment]
As per the comment above, I'm going to close this one for now. If anyone has further thoughts to share on this topic, feel free to open up [a new issue on Trac](https://core.trac.wordpress.org/newticket?component=Bundled+Theme). Thanks!
