### ISSUE TITLE
Consider renaming Homepage template

### ISSUE THREAD

**Issue by jameskoster** [WordPress/twentytwentytwo#225]
I think custom template names are most intuitive when they describe the template itself, rather than the projected use case. The "Page No Separators" and "Single No Separators" work well in this regard.

For example I may want to use the "Homepage" template for my Contact page, at which point the name starts to lose meaning. Not to mention that folks might confuse a template named "Homepage" with the home.html template.

**Comment by jffng** [comment]
Closed by #244.
