### ISSUE TITLE
Not able to read the text of Pattern 

### ISSUE THREAD

**Issue by kafleg** [WordPress/twentytwentytwo#226]
**Describe the bug**
While adding a Large header pattern on the page, I am not able to read the text. 

**To Reproduce**
1. Go to Pages > Add New 
2. Click on Content area and add patterns
3. Add Large Header pattern 
4. See an error

**Screenshots**
Here is the screenshot.
![Screenshot_2](https://user-images.githubusercontent.com/13062231/141277946-9433af54-f24f-4c5f-a822-0c6e0d6bbcf5.png)

**Comment by jffng** [comment]
Hi @kafleg, could you share your environment details? I'm unable to reproduce this on WordPress trunk, or 9.8.2 with Gutenberg trunk.

**Comment by jffng** [comment]
Going to close this one but please re-open with environment details if the issue persists, thanks!
