### ISSUE TITLE
The block contain unexpected or invalid content 

### ISSUE THREAD

**Issue by kafleg** [WordPress/twentytwentytwo#227]
Here is the screenshot of the issues,
![image](https://user-images.githubusercontent.com/13062231/141279190-ade97c10-6a9f-459c-9890-fad105f2f9e9.png)
Layered images with duotime block show this issue in the block editor.

**Comment by jffng** [comment]
I'm unable to reproduce this on WordPress trunk, or 9.8.2 with Gutenberg trunk. Could you share your environment details? Thank you!

**Comment by jffng** [comment]
Going to close this one but please re-open with environment details if the issue persists, thanks!
