### ISSUE TITLE
Update Navigation block in templates to use layout attributes

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/twentytwentytwo#230]
**Is your feature request related to a problem? Please describe.**

The Navigation block was updated in https://github.com/WordPress/gutenberg/pull/36169 to use the new layout controls, such as Query loop, Row, Buttons and Social Icons blocks also use. This means that the attribute structure in Navigation block markup has changed slightly, so it would be good to update the Navigation blocks in Twenty Twenty Two templates accordingly.

**Describe the solution you'd like**

Currently we have e.g.: `<!-- wp:navigation {"itemsJustification":"right","isResponsive":true} -->` . With layout, this should change to `<!-- wp:navigation {"layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"right"}} /-->`. (`is-responsive` is now on by default so it's no longer necessary to specify it.)

Nothing should break if using the old attributes, because there is a deprecation in place to handle them, but as this is the default theme shipping with 5.9 it would be nice to use the latest markup 🙂

**Comment by kjellr** [comment]
I tried giving this a go, but swapping out with the markup above (and a few other variations I tried) all threw markup errors: 

<img width="1092" alt="Screen Shot 2021-11-19 at 11 11 48 AM" src="https://user-images.githubusercontent.com/1202812/142655459-8fd4da23-d086-479e-8826-714202a184d5.png">

Is that still the markup we should be using?

**Comment by tellthemachines** [comment]
Oh, I see the issue. Sorry, there's a typo in my snippet; it shouldn't have the closing slash because the navigation block in the template has a closing tag already 🤦 

This should work:

`<!-- wp:navigation {"layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"right"}} -->`

**Comment by kjellr** [comment]
Thanks @tellthemachines! I have a PR here: https://github.com/WordPress/twentytwentytwo/pull/260
