### ISSUE TITLE
Post Content padding should match in the editor and front end

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#234]
_Consolidating two existing issues into one, since they're tightly related: #144 and #5_

## Current issue

Currently, there's a mismatch between the way site padding behaves in the post/page editor and the frontend. 

- In the editor, post content has no padding at all, regardless of its assigned alignment (default, wide, full).
- In the front-end, post content has appropriate default padding (since it's added to our default templates), but full-width items do not go to the screen edges.

Editor|Front End
---|---
<img width="990" alt="Screen Shot 2021-11-15 at 8 44 58 AM" src="https://user-images.githubusercontent.com/1202812/141792381-265bc397-664a-44de-bb82-b5577b85a92e.png">|<img width="828" alt="Screen Shot 2021-11-15 at 8 45 19 AM" src="https://user-images.githubusercontent.com/1202812/141792386-e73ecd75-205d-4d5f-9d43-530534b7ebe1.png">

## Target appearance

Our ideal solution is:

- Post content has a default padding that matches between the post/page editor and the front end.
- When a top-level item in the post content is assigned to be "full-width" it should go all the way to the screen edges.  

<img width="646" alt="Screen Shot 2021-11-15 at 8 47 49 AM" src="https://user-images.githubusercontent.com/1202812/141792752-db447064-639a-489e-b652-5c983a81e701.png">

## Upstream issues/PRs:

These issues would be solved universally with a solution to the following issue: 

- https://github.com/WordPress/gutenberg/issues/35607
- https://github.com/WordPress/gutenberg/pull/35919
- https://github.com/WordPress/gutenberg/pull/36214

**Comment by richtabor** [comment]
Are we thinking those issues would be solved for 5.9? If not, do we have a plan B?

**Comment by kjellr** [comment]
Yes, we'll figure this out. I think we'll get to a solution in https://github.com/WordPress/gutenberg/issues/35607.

A fallback would be to add CSS to handle this, but honestly I think that defeats the purpose of Gutenberg providing the layout control. 

@richtabor I'm curious if you've been dealing with this issue in any other themes?

**Comment by richtabor** [comment]
Yea, I’m seeing the exact issue. I’ve added a temporary negative margin hack to negate it, but its not awesome - nor is it a standardized solution that all themes would benefit from. If anything Gutenberg could work add the negative margin itself ha 🤷. 

I’m hoping for a standard that every full width aligned block can be adopted into automatically without any interference from a theme.

**Comment by kjellr** [comment]
I'm going to mark this as resolved for now because https://github.com/WordPress/twentytwentytwo/pull/291 has merged. But we can re-open as needed.
