### ISSUE TITLE
Add code quality checks to PRs

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#24]
We don't expect to have much CSS or PHP (and hopefully no Javascript at all!), but the code we do have should be checked against WP standards.

For reference, here's the same discussion for Twenty Twenty-One: https://github.com/WordPress/twentytwentyone/issues/9

**Comment by pattonwebz** [comment]
I know it's not right to comment without useful insights to share but I had to comment on this:

> (and hopefully no Javascript at all!)

Just to say how wonderful that sounds :)

**Comment by jffng** [comment]
Closed by #73.
