### ISSUE TITLE
BlockGap adds top margin to the header when Gutenberg is inactive

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentytwo#248]
**Describe the bug**

With WordPress trunk, the current theme version from GitHub, and with Gutenberg **not** enabled,
the blockGap adds a top margin to the header template part.
So there is a white space above the template part:

![the header has a black background color, above the header there is a white space](https://user-images.githubusercontent.com/7422055/142371979-4f62e725-ed1d-460f-a1fb-e041b0e3bdfd.png)

When Gutenberg current trunk, 12.00 RC 1, is enabled, the top margin is not applied.

So we are missing something that needs to be backported to WordPress core?
https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+is%3Aopen+label%3A%22Backport+to+WP+Beta%2FRC%22
Do you know which PR that might be?

**Comment by carolinan** [comment]
@youknowriad you may know the answer to the question above?

**Comment by kjellr** [comment]
Maybe this one? https://github.com/WordPress/gutenberg/pull/35425. That was the fix when we had this issue before.

**Comment by carolinan** [comment]
Except that was added in 11.8, which means it should already be included, no?

**Comment by youknowriad** [comment]
PHP changes backports are manual so it's definitely possible that some of this has been missed during the backports. Let's add this to the must haves to figure it out.

**Comment by kjellr** [comment]
I can confirm that https://github.com/WordPress/gutenberg/pull/35425 is the missing commit. I added a note upstream, added the backport tag, and added it to the 5.9 must-haves project. 

I'm going to close this one for now, but we can always re-open if this gets missed again in the next Beta.
