### ISSUE TITLE
Reconsider adding a search template

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentytwo#256]
In the site editor, when adding a new template, the user has the option to select between search and front page:

![Template selection in the site editor when clicking on "Add new" in the template list view](https://user-images.githubusercontent.com/7422055/142615491-0ebad24f-8e58-49c2-bd11-8e4f11370190.png)

If they select search, they are met with a blank template.
I think it would be easier for users to edit an existing template, if users want to make changes to the search results page.

**Comment by MaggieCabrera** [comment]
Shouldn't it inherit what's on index.html from just template hierarchy? I agree that TT2 should add a default search template because it should provide good defaults for most possible templates, but I'm thinking this is going to happen to a lot of themes and if the user doesn't add one, the frontend will show the fallback, why doesn't the editor do the same?

**Comment by carolinan** [comment]
It probably only checks if the template exists, not if it is exists but is blank.

**Comment by carolinan** [comment]
@MaggieCabrera Would you like to open a new Gutenberg issue for it? I am about to end my work week.

**Comment by MaggieCabrera** [comment]
> @MaggieCabrera Would you like to open a new Gutenberg issue for it? I am about to end my work week.

yep, will do!

**Comment by MaggieCabrera** [comment]
Opened https://github.com/WordPress/gutenberg/issues/36648 and I don't really know what to tag it to be honest

**Comment by kjellr** [comment]
Thanks for the issue. In the near term, I think adding a `search.html` template might make sense so that we can display the title of the search. (We can do that right? Does it use the Archive Title block?)

**Comment by Andrew-Starr** [comment]
> Thanks for the issue. In the near term, I think adding a `search.html` template might make sense so that we can display the title of the search. (We can do that right? Does it use the Archive Title block?)

Sadly no, the Archive Title does nothing when used in a search context :(

**Comment by kjellr** [comment]
If that's the case, I'm not sure there's much benefit to adding a search template at this point.

**Comment by carolinan** [comment]
I think the benefit of not having a blank template in the site editor is bigger than the trouble of having to add a heading block?

**Comment by jameskoster** [comment]
> Sadly no, the Archive Title does nothing when used in a search context :(

We should probably open an issue in core for that. 

It is closely related to https://github.com/WordPress/gutenberg/issues/36609 and could combine to form an "improving search" initiative.

**Comment by kjellr** [comment]
> I think the benefit of not having a blank template in the site editor is bigger than the trouble of having to add a heading block?

Yes, but this should really be fixed upstream in #36648, not just in the theme. Let's leave this issue open to track the issue on our end, but push to have it fixed upstream.

**Comment by carolinan** [comment]
My worry is that there are a very large number of requests for things that needs to be addressed for 5.9,
while it should be fixed upstream, there are perhaps more important usability related problems with the editor and UX that needs to be prioritized.
An improved query title block can be added in Gutenberg at a later release, and it can be fully tested there until 6.0, or 6.1 if needed.

**Comment by kjellr** [comment]
It's true, but we now have a longer timeline, so we'll see. I'll milestone this issue so we can be sure to keep track of it either way.
