### ISSUE TITLE
Update theme folders to "templates" and "parts"

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#264]
Now that https://github.com/WordPress/gutenberg/pull/36647 has been merged, we should update the the following folder names: 

- `block-templates` ➡️  `templates`
- `block-template-parts`  ➡️  `parts`

**Comment by kjellr** [comment]
@mburridge has volunteered to take this on. 🙌

**Comment by ndiego** [comment]
I believe this can be closed.

**Comment by kjellr** [comment]
Yep, all set. Thanks everyone!
