### ISSUE TITLE
Try and place patterns in default categories instead of declaring our own

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#267]
Currently, Twenty Twenty-Two declares five new pattern categories: 

- Twenty Twenty-Two General
- Twenty Twenty-Two Footers
- Twenty Twenty-Two Headers
- Twenty Twenty-Two Posts
- Twenty Twenty-Two Pages

Most of these categories should/will/do exist in Gutenberg by default, and it would be great if we could hook into them automatically rather than declare our own duplicate, lengthy category names. 

For example, it would be ideal if we could just place our theme header patterns in the normal "Headers" category, and have them show up before the default set. 

## Screenshot

<img width="1105" alt="Screen Shot 2021-11-30 at 12 57 38 PM" src="https://user-images.githubusercontent.com/1202812/144102135-645249e5-705e-4d18-8758-576961566bbc.png">

**Comment by shaunandrews** [comment]
I've seen it mentioned a few times that perhaps we should group these categories by the way their created; Having a "Twenty Twenty-Two" section or a "Coblocks" section, but this still leads to having duplicate categories like in the mockup below:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/191598/144127660-40837cbc-3ae6-4575-80b5-643d4d92fa00.png">

> it would be ideal if we could just place our theme header patterns in the normal "Headers" category, and have them show up before the default set.

Agreed 100%. I think we can even go a little further and highlight the theme-recommended patterns at the top of the grid:

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/191598/144128101-f7ae8ca8-bf36-4320-af9f-e7b473c7e170.png">

Then, the sidebar can show an item for the theme's patterns along with items any plugin provided patterns — this avoids having duplicated categories, and keeps the list clean.

**Comment by ndiego** [comment]
I have some ideas how this all could functionally work. Will work on getting that more formalized this week.

**Comment by kjellr** [comment]
I took a stab at adding these to the default categories in the theme itself. A couple observations: 

- I was able to get the Query patterns added to the default "Query" category, [as established in Gutenberg](https://github.com/WordPress/gutenberg/blob/2d3d0f368385b271c20ece697e77714e3b5c1e99/lib/block-patterns.php#L14) just fine. But honestly, I think that category name is really confusing for users. We should probably change it to "Posts" here, and try to get Gutenberg to follow suit. 
- I'm unable to place items in the "Headers" category. I imagine that is because it comes from the pattern directory. @ryelle do you happen to know if it's possible for a theme to override that? Our goal would be to take the patterns that are defined here in the theme, and place them in the pre-existing "Headers" category in the editor.

**Comment by ryelle** [comment]
"Headers" is a core category, so it should work- the slug is `header`, though. Other than that, the approach in #284 looks good to me.

**Comment by kjellr** [comment]
Ha, thank you for catching that! I'll give it a try. 🙌
