### ISSUE TITLE
Mobile menu design need to fix 

### ISSUE THREAD

**Issue by kafleg** [WordPress/twentytwentytwo#269]
**Describe the bug**
I have created a primary menu with 3 main menus and sub-menu items. The design on the desktop view is fine, but in the mobile view, it's not so perfect. See the screenshot to understand the issue. 
**To Reproduce**
1. Go to Appearance > Navigation Menus 
2. Add New Menu
3. Go to Edit Site and add menu items to the menu
4. Save the template parts and view the site in front end mobile view 

**Screenshots**
![image](https://user-images.githubusercontent.com/13062231/144402452-0405f4ac-3adc-479f-bad6-95ce2c0ba2fd.png)

**Device inphone:**
 - Device: Dell PC
 - OS: Windows 
 - Browser: Edge
 - Version: 5.9 Beta

Note: No any plugins installed or activated.

**Comment by kjellr** [comment]
I haven't tested this yet, but this would require an upstream bug if folks can reproduce it. Twenty Twenty-Two uses the default responsive menu behavior/appearance. 

cc @jasmussen

**Comment by jasmussen** [comment]
Yep, thanks for the report, thanks for the ping. This issue should be fixed by https://github.com/WordPress/gutenberg/pull/36991.

**Comment by kjellr** [comment]
Awesome, thanks everyone! I'll close for now, but we can re-open if it pops up again.
