### ISSUE TITLE
[Quote]: Border issues

### ISSUE THREAD

**Issue by dashkevych** [WordPress/twentytwentytwo#278]
**Describe the bug**
The theme includes the following settings for the Quote block in `theme.json`:

```
"core/quote": {
  "border": {
    "width": "0 0 0 1px"
  }
}
```

It works great in a default block layout (with left alignment). However, issues appear when changing alignment from left to right.

**To Reproduce**
1. Add Quote block to the post.
2. Keep default alignment.
3. Add another Quote block to the post.
4. Change text alignment to right in the 2nd Quote block. 
5. See issue.

**Expected behavior**
The block should have the same styling, except the location of a side border, when setting either left alignment or right alignment. 

**Screenshots**

Website (different border width):
<img width="783" alt="website_preview" src="https://user-images.githubusercontent.com/3655965/145088052-3949a4e8-a473-40c3-aa8a-0a9ec73633bc.png">

Editor (missing a side border):
<img width="776" alt="editor_preview" src="https://user-images.githubusercontent.com/3655965/145088099-91435f5c-7779-44da-8fd5-34361191cc4f.png">

**Comment by kjellr** [comment]
Thanks, @dashkevych! I've opened an upstream issue for Gutenberg to either make the front-end match the editor, or to enable a more flexible way to set the border width via theme.json. 

I'll keep an eye on that, and will adjust Twenty Twenty-Two if necessary.
