### ISSUE TITLE
BETA 2: white screen at "Browse all Templates".

### ISSUE THREAD

**Issue by elbsegler63** [WordPress/twentytwentytwo#282]
**To Reproduce**
1. Go to 'Appearance - Editor (Beta) - Headline
2. Click on 'Browse all Templates"
4. Something can be seen for maybe a quarter of a second. After that the screen is white.

**Expected behavior**
I am expecting a list of all templates that are available.

**Device**
 - Browser:  Firefox and Chrome
 - Version:the latest version is always installed

WordPress 5.9 BETA 2
TT2 coming with WordPress 5.9 Beta
Plugin: WordPress Beta Tester 3.1.4

**Additional context**
Before I added an new Custom-Template with a Custom Header and a Custom Templatepart,

![browse all templates](https://user-images.githubusercontent.com/85250773/145180388-830d5b63-63d4-47d7-91a7-b0a9bd260253.PNG)

![browse all templates empty screen](https://user-images.githubusercontent.com/85250773/145180404-9891ec14-a01f-4193-aaea-2059550390fd.PNG)

**Comment by kafleg** [comment]
Tested with RC 5.9 Beta 2 but there are no such issues found. There is no white screen appearing.

**Comment by kjellr** [comment]
I'm not seeing this either. I'll leave this open for an extra day or so in case someone else can reproduce. But in general if this is an issue I think it belongs in the upstream [Gutenberg repository](https://github.com/wordpress/gutenberg).

**Comment by aristath** [comment]
Can't replicate either

**Comment by elbsegler63** [comment]
Thanks for the feedback.
I'll set up a new system and go through the steps again. I will contact you in 16 hours at the latest.

**Comment by elbsegler63** [comment]
Although I tried several times, I was unable to reproduce the "error" today.
So I close this issue.
Many thanks for your help.
