### ISSUE TITLE
blockTypes / Pattern Question

### ISSUE THREAD

**Issue by bgardner** [WordPress/twentytwentytwo#287]
**Description**
Just a general question to help inform our efforts. What is the significance of code like below, as found in each pattern file:

```
'blockTypes' => array( 'core/template-part/header' ),
```

**Comment by kjellr** [comment]
This property was introduced in 5.8: 
https://make.wordpress.org/core/2021/07/12/miscellaneous-block-editor-api-additions-in-wordpress-5-8/

It tells the editor to associate the pattern with the block type specified, for use in pattern transforms, or in the pattern carousel here: 

<img width="683" alt="Screen Shot 2021-12-09 at 9 29 52 AM" src="https://user-images.githubusercontent.com/1202812/145415129-526152f3-4a44-4cc9-a313-bbaa17821d0c.png">

**Comment by bgardner** [comment]
Ah, gotcha. Thanks @kjellr.
