### ISSUE TITLE
Document a minimal child theme example

### ISSUE THREAD

**Issue by LantosIstvan** [WordPress/twentytwentytwo#288]
**Description**

I created a simple child theme for Twenty twenty-two, only with `style.css`, without `functions.php`:

```css
/*
 Theme Name: Twenty Twenty-Two Child
 Theme URI: https://github.com/wordpress/twentytwentytwo/
 Template: twentytwentytwo
 Version: 0.1
*/
```

But the header image not displayed on the News page.
![FireShot Capture 1302 - Hírek – WordPress 5 9 Beta Test - app test](https://user-images.githubusercontent.com/5021728/145432105-2e78d5a9-67bf-48e0-a82b-a8a2710cb583.png)

What we should see:
![FireShot Capture 1303 - Hírek – WordPress 5 9 Beta Test - app test](https://user-images.githubusercontent.com/5021728/145432112-17b12611-3cfe-43fd-9d0a-e406514c1313.png)

Wordpress version: 5.9-beta2-52346

I'm not sure how to create a proper child theme for the new block themes. Can you provide a minimal example?

**Comment by tinjure20** [comment]
Here is a [pull ticket at GitHub](https://github.com/WordPress/theme-experiments/pull/292) to try a few Twenty Twenty-Two child themes with five examples and [here you can find their examples codes](https://github.com/WordPress/theme-experiments/tree/add/tt2-child-themes).

**Comment by LantosIstvan** [comment]
Header images still not present within the example child themes from the theme-experiments repo.

**Comment by kjellr** [comment]
:wave: The header image issue was fixed yesterday [in this commit](https://github.com/WordPress/twentytwentytwo/pull/283).

**Comment by LantosIstvan** [comment]
Thank You!
