### ISSUE TITLE
String translation in templates

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentytwo#30]
There are currently a few strings in the block templates that we will need to figure out what to do with from a translation / i18n perspective. Let's use this issue to discuss and track what to do there: 

- [x] Footer Credit
- [x] 404

Related Gutenberg issues / explorations:

- https://github.com/WordPress/gutenberg/issues/27402
- https://github.com/WordPress/gutenberg/pull/33217
- https://github.com/WordPress/gutenberg/pull/33192

**Comment by carolinan** [comment]
In my opinion, it is not for the theme to solve. I would leave them as is, because multi-lingual is not until phase 4.

**Comment by Soean** [comment]
Multilingual will solve the problem to translate and save the content of websites in different languages. Themes and Templates should be ready for localization and translation.

**Comment by carolinan** [comment]
And they are, because you can add your own text.

**Comment by Soean** [comment]
So we can't translate it globally per language, and each user has to translate it themselves and override the template, if I understand it correctly.

**Comment by aristath** [comment]
> So we can't translate it globally per language, and each user has to translate it themselves and override the template, if I understand it correctly.

Correct. If they want it on a different language, they can simply edit the templates. It's not like in classic themes where these were not user-editable... So IMO it's not really a blocker 👍

**Comment by kjellr** [comment]
While the user _could_ go and edit those strings, they won't know that they need to. In that past, those have always been translated automatically. And for example, one of these strings is on the 404 page — it's quite likely a user won't know they need to look there and manually translate that string.

**Comment by carolinan** [comment]
But it is not for the theme to solve, because it is not specific to this theme.
It is a much bigger issue within Gutenberg and also with how the WordPress project will introduce block themes. It may be solved with documentation until there is a complete solution.

It is not something that can be solved before the feature freeze unless there is a decision from the 5.9 leads that it will be prioritized, and the contributors focus on it, because it has not had movement since December 2020.

**Comment by jffng** [comment]
Since the pattern block was merged, this is unblocked. We should replace those strings with patterns. For the 404, it may make sense to make the pattern include all of this: 

<img width="561" alt="Screen Shot 2021-10-29 at 12 26 08 PM" src="https://user-images.githubusercontent.com/5375500/139470135-e495e55d-9de1-4732-a96e-65a9ea070bc2.png">

What do you think @kjellr?

**Comment by kjellr** [comment]
Yeah, might as well. Let's put it at the very bottom of the "General" patterns list [until we can hide it](https://github.com/WordPress/gutenberg/issues/36084).
