### ISSUE TITLE
Using CSS variables for wp-container max-width

### ISSUE THREAD

**Issue by larsadolfsen** [WordPress/twentytwentytwo#303]
I suggest using CSS variables for max-width on .wp-containers when Change Alignment is set to None and Wide Width

This would make it much easier to change the width of templates overall, but also for custom styling of elements..

**Comment by kjellr** [comment]
👋 Hey there. At some point, users should be able to edit those values directly in [the Global Styles panel](https://github.com/WordPress/gutenberg/issues/35955), which should make them far easier to edit. 

In general though, the styles that control the layout are defined in theme.json and then generated by Gutenberg, so this would have to be done on the Gutenberg level. If you'd like to open an issue to suggest the use of CSS variables for this, feel free to open a Gutenberg issue here: 

https://github.com/WordPress/gutenberg/issues/new?assignees=&labels=&template=Feature_request.md

**Comment by kjellr** [comment]
Now that we're nearing release, I'm going to close this issue. If anyone has further thoughts to share on this topic, feel free to open up [a new issue on Trac](https://core.trac.wordpress.org/newticket?component=Bundled+Theme) or in [the Gutenberg repository](https://github.com/WordPress/gutenberg/issues/new?assignees=&labels=&template=Feature_request.md).
