### ISSUE TITLE
Edit page

### ISSUE THREAD

**Issue by Roger-fotograf** [WordPress/twentytwentytwo#313]
**Describe the bug**

**To Reproduce**
1. Go to 'https://rvbild.se/Staging/'
2. Click on 'edit page'
3. Scroll down to 'Highlighted quote'
4. bp@https://rvbild.se/Staging/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=67d21aeb1aa1df344a63b445f5fd8f8e:47:6723
Le@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:100:4
Pj@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:231:185
di@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:168:307
Nj@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:168:238
sc@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:168:98
gf@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:111
gf@[native code]
@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:231
unstable_runWithPriority@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:27
$g@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:178
ja@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:113
Pa@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:157:214
Me@https://rvbild.se/Staging/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:110:252
Me@[native code]
e@https://rvbild.se/Staging/wp-content/plugins/gutenberg/build/data/index.min.js?ver=05fb85e566a8f20348b121e948876ca4:1:21707
t@https://rvbild.se/Staging/wp-content/plugins/gutenberg/build/data/index.min.js?ver=05fb85e566a8f20348b121e948876ca4:1:21774
@https://rvbild.se/Staging/wp-content/plugins/gutenberg/build/data/index.min.js?ver=05fb85e566a8f20348b121e948876ca4:1:16978
@https://rvbild.se/Staging/wp-content/plugins/gutenberg/build/data/index.min.js?ver=05fb85e566a8f20348b121e948876ca4:1:15265
p@https://rvbild.se/Staging/wp-content/plugins/gutenberg/build/data/index.min.js?ver=05fb85e566a8f20348b121e948876ca4:1:6880
@https://rvbild.se/Staging/wp-content/plugins/gutenberg/build/data/index.min.js?ver=05fb85e566a8f20348b121e948876ca4:1:13273
@https://rvbild.se/Staging/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=67d21aeb1aa1df344a63b445f5fd8f8e:78:9669
u@https://rvbild.se/Staging/wp-content/plugins/gutenberg/build/rich-text/index.min.js?ver=31f565665c751c8f3844cf32c8a688ab:5:6894

**Expected behavior**
Tru to edit the Highlighted quote'

**Screenshots**
 - Device: MacBook Pro (16 tum, 2019)
 - OS: Monterey 12.1
 - Browser: Safari
 - Version:Version 15.2 (17612.3.6.1.6)

**Additional context**
![Bild 2021-12-26 kl  09 22](https://user-images.githubusercontent.com/67589236/147403109-478e935c-6797-42c7-949f-a0d0231bcffc.jpg)

**Comment by carolinan** [comment]
Hi Roger
This seems to be a plugin issue, the block mentioned in the issue, "Highlighted quote" is not a WordPress core block.

**Comment by Roger-fotograf** [comment]
Ok Sorry. Can I use any plugin?

**Comment by carolinan** [comment]
You can try any plugin, but there is no way for the theme developers to test which plugins are compatible with block themes.

**Comment by kjellr** [comment]
Now that we're nearing release, I'm going to close this issue. If anyone has further thoughts to share on this topic, feel free to open up [a new issue on Trac](https://core.trac.wordpress.org/newticket?component=Bundled+Theme).
