### ISSUE TITLE
Navigation under the Comment Block is not cleared after floating

### ISSUE THREAD

**Issue by alberto-marin** [WordPress/twentytwentytwo#314]
**Describe the bug**
When breaking the comments into pages, the comment navigation is missing CSS styles to clear those elements after float.

**To Reproduce**
1. Create a post and make a few comments, let's say 13 (why not?)
2. Activate Break comments into pages under Settings -> Discussion. Set to an amount that will ensure the comment navigation to show.
3. Visualise the post with the comments
4. See CSS problem

**Expected behavior**
Elements before and after the wp comment block containing the navigation should be cleared and avoid overlapping.

**Screenshots**

**Current problem:**

<img width="1029" alt="top-before" src="https://user-images.githubusercontent.com/10046225/147603584-9d793132-5868-4acf-8b66-3390cc553bc3.png">
<img width="1030" alt="bottom-before" src="https://user-images.githubusercontent.com/10046225/147603613-3c765658-94ba-4db3-8ec5-c2255d9ffef2.png">

**Expectation:**

<img width="1029" alt="top-after" src="https://user-images.githubusercontent.com/10046225/147603659-0152fc79-ead3-443a-ac51-2a6d20256300.png">
<img width="1029" alt="bottom-after" src="https://user-images.githubusercontent.com/10046225/147603680-9c0f6dee-63cd-4e8e-a6c4-e520269fc3ac.png">

**Device inphone:**
 - Device: macbook pro M1
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: 96.0.4664.110 (Official Build) (arm64)

**Proposed solution**

```
.wp-block-post-comments .navigation {
    margin-bottom: 1.4em;
}
.wp-block-post-comments .navigation:before, 
.wp-block-post-comments .navigation:after {
    content: '';
    display: table;
    clear: both;
}
```

**Comment by kjellr** [comment]
Thanks for flagging — I think this probably needs an issue in Gutenberg akin to the one created in response to https://github.com/WordPress/twentytwentytwo/issues/44: https://github.com/WordPress/gutenberg/pull/35958

**Comment by kjellr** [comment]
This has been reported upstream here: https://github.com/WordPress/gutenberg/issues/38188

Thanks again!
