### ISSUE TITLE
H1 in the footer and H1 in the Header in addition to the H1 in the beginning of the page content

### ISSUE THREAD

**Issue by oglekler** [WordPress/twentytwentytwo#321]
From an SEO point of view, this is not the best design if there are 3 H1s on the same page:

![2022-01-05_19-47-23](https://user-images.githubusercontent.com/16874687/148256331-cd7bc938-d158-443b-84f9-2db567edad60.png)

![2022-01-05_19-40-13](https://user-images.githubusercontent.com/16874687/148255467-02c9abf6-09bc-4261-9a9b-324e532918f7.png)

I suggest replacing H1 in the Header in the Footer to divs.

**Comment by kjellr** [comment]
Hey @OlaIola, the use of multiple H1s has been discussed over in https://github.com/WordPress/twentytwentytwo/issues/233. In short, we're keeping them that way for now. 

The footer one is a bug though — that was already fixed once in #40 but it was mistakenly undone. I've opened #322 to fix that.
