### ISSUE TITLE
Header options

### ISSUE THREAD

**Issue by dannymekic** [WordPress/twentytwentytwo#324]
**Is your feature request related to a problem? Please describe.**
At the moment the header and menu bar is only available statically at the top of the page. It will be desirable for some website owners to keep the header/menu bar visible as the user scrolls down, or have the header/menu bar re-appear as soon as a visitor starts scrolling up the page.

**Describe the solution you'd like**
 Is it possible to include such basic functionalities in the theme?

**Comment by critterverse** [comment]
+1

There has been some discussion around this feature so far in https://github.com/WordPress/gutenberg/issues/30121 :)

**Comment by kjellr** [comment]
Thanks for the issue @dannymekic, and for the context, @critterverse! Since this would rely on functionality in Gutenberg, I'm going to close this theme issue for the time being. We can continue discussion in https://github.com/WordPress/gutenberg/issues/30121 if necessary!
