### ISSUE TITLE
Should all header patterns have the core/site-logo block?

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentytwo#329]
**Is your feature request related to a problem? Please describe.**
It's difficult to add a Site Logo block to an existing pattern. It requires adding a Row block (Group) then adding the site-title and additional site-logo block to it, the adjusting it to display beside the existing navigation. It's not an easy task — but removing a site-logo block is (if the user chooses not to have the logo).  

**Describe the solution you'd like**
Consider updating the header patterns to consistently include site-logo blocks. 

**Screenshot**
<img width="366" alt="CleanShot 2022-01-10 at 19 43 09@2x" src="https://user-images.githubusercontent.com/1813435/148861501-ab2fa1ba-ed7e-45a9-8dc7-e88d59c551f2.png">
*I added the TT2 label to tell which were TT2 and which were not for myself :)

**Comment by kjellr** [comment]
Thanks for the issue. I don't think all patterns should include one — some folks will want a logo and other won't. There is a site logo in the default header, so at least there's that. 

In retrospect, we could've probably included a handful more patterns that do feature a site logo, but we aren't going to add more in at this point in RC. It's possible we can add some later, but I think once the pattern directory hosts some header patterns we probably won't need to. 

Regarding the usability issues around adding one in to a row block — do you think there's a Gutenberg issue worth filling in there somewhere? 

In any case, I'm going to close this for now, but we can keep discussing if anyone has further thoughts!
