### ISSUE TITLE
Comment form is missing basic styles

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#33]
We don't want to do anything custom here, so I think these should look good out of the box. They are currently tiny and do not inherit the normal text size. Also that "Save my name, email..." lockup is pretty messy. Gutenberg should take care of that natively. 

There's already a Gutenberg issue to fix this: https://github.com/WordPress/gutenberg/issues/26865

<img width="736" alt="Screen Shot 2021-10-06 at 4 30 24 PM" src="https://user-images.githubusercontent.com/1202812/136278618-07769aba-808f-45dd-affb-360f2799a5ec.png">

<img width="763" alt="Screen Shot 2021-10-06 at 4 34 14 PM" src="https://user-images.githubusercontent.com/1202812/136278987-eea7c3fd-00fc-41e5-9882-987c37cc3f22.png">

**Comment by jffng** [comment]
Actually following the Gutenberg issue above, it sounds like @karmatosed may be taking a look at supplying some better defaults in https://github.com/WordPress/gutenberg/pull/27009, so I'll follow along there! 🙏

**Comment by kjellr** [comment]
Should be all set now that https://github.com/WordPress/gutenberg/pull/35704 has been merged. 👍
