### ISSUE TITLE
Block Editor Dimensions: PX/VH/VW/EM text options partially hidden in Firefox

### ISSUE THREAD

**Issue by itsjustdj** [WordPress/twentytwentytwo#335]
When editing the dimensions on a block, specifically Padding, the text is partially hidden in the input window.

**To Reproduce**
1. Go to Appearance>Editor
2. Click on any block
3. Scroll down to Dimensions, choose + Padding

**Expected behavior**
The text should appear fully in the input window.

<img width="285" alt="CleanShot 2022-01-11 at 16 12 57@2x" src="https://user-images.githubusercontent.com/71471241/149042976-646e1c8d-977b-4b71-b213-9075115771f2.png">

**Device**
 - Device: Macbook Pro M1
 - OS: Mac OS
 - Browser: Firefox
 - Version: 95.0.2

**Additional context**
This seems to only happen in Firefox. I also tested it in Safari and Chrome and in those browsers it's fine.

**Comment by kjellr** [comment]
Hi there! This is a bug with Gutenberg, not specifically with Twenty Twenty-Two. I'll add your details to [the existing issue in the Gutenberg repository](https://github.com/WordPress/gutenberg/issues/24280), and close this duplicate one. Thank you for the report!
