### ISSUE TITLE
Add `hacktoberfest` topic

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/twentytwentytwo#34]
Can we add the `hacktoberfest` topic to the repo throughout October to encourage some additional participation and contributions?

**Comment by audrasjb** [comment]
100% agree 👍

**Comment by kafleg** [comment]
Totally agree and we need to do it soon.

**Comment by pattonwebz** [comment]
@kjellr @jffng do one of you have the access needed to add this?

**Comment by jffng** [comment]
Added 👍 
<img width="312" alt="Screen Shot 2021-10-08 at 11 00 24 AM" src="https://user-images.githubusercontent.com/5375500/136579418-8696f12c-689e-4506-a50e-8b6a8fe745e0.png">

**Comment by pattonwebz** [comment]
@jffng your a star :star: . Thank you!
