### ISSUE TITLE
SoundCloud blocks do not sit right in the post layout

### ISSUE THREAD

**Issue by aleksblendwerk** [WordPress/twentytwentytwo#340]
I just installed WordPress 5.9 RC3 (via zip download, no further manual updates) and made a test post with a few paragraphs and a list followed by a SoundCloud block. This block looks right while editing the post but on the actual page, the width of the `iframe` does not fit the width of the actual content and changing the alignment will make it look even more odd. I've only tried this with Chrome on desktop.

Doing the same with a YouTube block, it behaves as I would expect.

I am not sure where in the WordPress universe this report belongs, just thought I'd report it.

**Comment by kjellr** [comment]
Thank you for the report, @aleksblendwerk! It looks like this is the same bug noted here: https://github.com/WordPress/gutenberg/issues/37287

I'll close this one for now, but feel free to add more details in that issue if you'd like! Thanks again!

**Comment by aleksblendwerk** [comment]
This is a dupe then indeed. Thank you, @kjellr and all the best for the upcoming release!
