### ISSUE TITLE
general-pricing-table: Shouldn't the heading levels be consistent and well structured?

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/twentytwentytwo#341]
**Description**
h3 for Pigeon but h2 for Sparrow and Falcon. Isn't this considered to be badly structured?

![image](https://user-images.githubusercontent.com/2474435/150486699-68fc52eb-19cc-4cbf-9657-f6015159929d.png)

**Comment by kjellr** [comment]
Yeah, that's an oversight. Thanks for filing the issue!

There aren't going to be any more bugfix theme commits before the 5.9 code freeze on Monday, but we'll migrate this issue over to Trac after release. 

Thanks again.

**Comment by kjellr** [comment]
This issue has been reported on Trac here: https://core.trac.wordpress.org/ticket/54929
