### ISSUE TITLE
404 search label should be translated

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentytwo#342]
**Describe the bug**
The `hidden-404` pattern contains a label that is not marked for translation. We should update this in core after 5.9 is released and mark it for inclusion in 5.9.1.

https://github.com/WordPress/twentytwentytwo/blob/trunk/inc/patterns/hidden-404.php#L14

**Comment by kjellr** [comment]
This issue has been migrated over to Trac here: https://core.trac.wordpress.org/ticket/54928
