### ISSUE TITLE
Twenty Twenty-Two not working with WordPress 5.9-RC3-52617

### ISSUE THREAD

**Issue by AngelCherub** [WordPress/twentytwentytwo#343]
Site updated automatically to WordPress 5.9-RC3-52617.

On the Themes page, it says Twenty Twenty-Two doesn't work with this version of WordPress. The theme cannot be activated.

Have reinstalled WordPress 5.9-RC3-52617.

Have deleted Twenty Twenty-Two and then reinstalled WordPress 5.9-RC3-52617. Again, Twenty Twenty-Two cannot be activated.

I know there is a requirement ([now](https://github.com/WordPress/twentytwentytwo/pull/326)) to be running 5.9 rather than 5.8, but the site is running 5.9 and the error message still appears. Is that expected?

Angel

**Comment by desrosj** [comment]
Hi Angel,

This is a known issue and is being tracked here: https://core.trac.wordpress.org/ticket/54882.

According to how version strings are evaluated, 5.9-RC3 is lower than 5.9, so WordPress is preventing it from being activated.

It looks like you may be using the beta tester to test, which will update you to the latest nightly version of the upcoming release daily.

For the time being, you can change the `Tested up to: 5.9` line in the theme's `style.css` file to have a value of `5.8` instead, and you should be able to test without issue!

**Comment by AngelCherub** [comment]
Thank you, @desrosj. That edit makes the theme selectable again. I apologise if my post was unnecessary / wrong in any way. New to nearly all of this, so somewhat fumbling about. Appreciate your patience and help.

Angel
