### ISSUE TITLE
Unclear that the default homepage is a blog post and cannot be editing

### ISSUE THREAD

**Issue by brianhogg** [WordPress/twentytwentytwo#344]
**Is your feature request related to a problem? Please describe.**
I went to edit the homepage (which by default is the blog posting listing, with the "Hello world!" post displayed), and was trying to edit the title and test displayed. After I minute I realized that I couldn't because it's generated content, but to a new user they'd never realize.

**Describe the solution you'd like**
An indication that you are editing the blog post index and what the limitations are (even a quick 1-2 step walkthrough to a new user of Twenty Twenty-Two), or perhaps making the default homepage a Page rather than a post listing.

**Comment by kjellr** [comment]
Thanks for the feedback. It sounds like the confusion you're describing is likely a concern for all block themes, and perhaps it's necessary for Gutenberg to provide some clearer onboarding. Perhaps this would merit an issue [over in the Gutenberg repository instead](https://github.com/WordPress/gutenberg/issues/new/choose)?

Regarding the theme itself: At this point, there's a code freeze for release, so we're not making any further changes to the theme for its initial launch. 

We're in the process of closing this repository and migrating the theme's development over to Trac — if you feel there's something the theme can do to improve the experience here, feel free to [open an issue over there](https://core.trac.wordpress.org/newticket?component=Bundled+Theme) and we can continue discussing. 

Thanks again for the report!
