### ISSUE TITLE
Blank screen displayed for custom post type

### ISSUE THREAD

**Issue by davidfcarr** [WordPress/twentytwentytwo#345]
I'm trying to debug the interaction between this theme and the rsvpmaker custom post type from an events management plugin of mine. When trying to view this content, a blank screen is displayed but no error is logged.

Guessing it might have something to do with changes to the template hierarchy.

Normally, posts of this post type would be displayed in single.php unless a single-rsvpmaker.php has been defined. So I would expect it to display in the single.html template of Twenty Twenty Two.

What else should I check? Have other plugin developers reported similar issues?

**Comment by kjellr** [comment]
This issue has been migrated over to Trac here: https://core.trac.wordpress.org/ticket/54896
