### ISSUE TITLE
Fix phpstan issue with enqueue function

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/twentytwentytwo#35]
>phpstan is throwing the following error which I'm confused by, so I've had to `--no-verify` in order to commit:
>
> ```
> ------ -------------------------------------------------------- 
>  Line   functions.php                                           
> ------ -------------------------------------------------------- 
>  35     Parameter #4 $ver of function wp_enqueue_style expects  
>         bool|string|null, array|string|false given.             
> ------ -------------------------------------------------------- 
> ```

_Originally posted by @jffng in https://github.com/WordPress/twentytwentytwo/issues/26#issuecomment-937118508_

Because `wp_get_theme()->get()` can return `array|string|false` but the `wp_enqueue_style()` can only accept `bool|string|null` this error is flagged. We can either do a type check in advance to verify string or we can pass a static string.

I will open a PR with a typecheck and ternary that satisfies this error but the code doesn't look right. We might just want to flag it as ignored as the solution.

**Comment by jffng** [comment]
Thanks for following up.

> We might just want to flag it as ignored as the solution.

What do you think about doing this instead?

**Comment by pattonwebz** [comment]
> What do you think about doing this instead?

I believe this is the cleanest solution here - to just keep the flag to ignore this in static analysis. Let's leave this issue and PR open for a little while though to get others thoughts :)
