### ISSUE TITLE
Support gradients

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentytwo#41]
We should consider supporting gradients, as the theme should showcase what's possible/inspire folks. 

I have some ideas I can pitch to fit the vibe that I'll push. :)

**Comment by LittleBigThing** [comment]
There are some nice, subtle gradients suggested in the [Figma prototype](https://www.figma.com/file/76mfUcaK4QDlrXElk8MK3H/Twenty-Twenty-Two?node-id=2166%3A3521) as well.
