### ISSUE TITLE
Address a floating issue on the <main> element

### ISSUE THREAD

**Issue by audrasjb** [WordPress/twentytwentytwo#44]
I believe we need to add an `overflow: hidden` declaration to the `<main>` element on each template to avoid floating issues. Not sure where is the best location for this CSS declaration though.

Issue:

![screencapture-localhost-8888-twentytwentytwo-about-clearing-floats-2021-10-07-00_50_16](https://user-images.githubusercontent.com/1590998/136294350-fcc66435-d420-4ff2-a5c8-7d6b2d77d159.png)

**Comment by kjellr** [comment]
Since this would effect any block theme, I've opened an upstream PR here: https://github.com/WordPress/gutenberg/pull/35958

**Comment by kjellr** [comment]
Fixed upstream: https://github.com/WordPress/gutenberg/pull/35958

Thanks for raising the issue!
