### ISSUE TITLE
Stretched image on home page

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentytwo#48]
<img width="914" alt="Screenshot 2021-10-07 at 09 35 11" src="https://user-images.githubusercontent.com/3593343/136340183-ae2e25f0-9f91-403c-b42b-1b1577594b27.png">

This is happening to me on Firefox and on my iPhone too, testing on Kjell's staging website. I believe this should be solved by https://github.com/WordPress/gutenberg/pull/30092

**Comment by kjellr** [comment]
Yeah, that's the issue that's causing it. Should be solved in the next release now that it's been merged. 👍
