### ISSUE TITLE
Alternate Styles

### ISSUE THREAD

**Issue by nickhamze** [WordPress/twentytwentytwo#53]
First off the theme is beautiful as expected as @kjellr is da bomb. The aspect I'm a bit disappointed over is the alternative styles. While they are again very nice they are very similar to the default style.

While it's possible for users to set their own colors/fonts I would love to see some built in styles that are a bit different. While the default themes are functional they are also suppose to be inspirational. I'd love to see something that shows users and developers what's possible with the new tools being developed.

As you said in your it's so easy to use different colors and fonts to make something that looks totally different let's that that concept to 11. 

Wouldn't it be cool to have:
- a bright pink style with punk rock typography.
- something spacey with geometric fonts that belong on the side of the Enterprise
- a 50s color palette along with a font like this: https://fonts.google.com/specimen/Fontdiner+Swanky?category=Display#standard-styles

Any way you get the idea. Those were just some random ideas but the basic premise let's help make a web a bit less boring and reenergize the community at the same time but offer variations that are different. Maybe this would be a cool way to get more designers interested in theming too. By picking a few colors and fonts they could contribute to core.

**Comment by kjellr** [comment]
This sort of thing will be low priority, but I’m going to just note a few quick things: 

1. I love weird stuff, and would like to build more weird stuff.
2. What we’re thinking of as “alternate styles” may end up just being entirely different themes. If that's the case, we as a community can build as many of those as we want — what's mocked up in the announcement post, and beyond. 
3. Either way, as noted at the bottom of [the announcement post](https://make.wordpress.org/core/2021/10/06/introducing-twenty-twenty-two/), I’d love for us to build + release default themes more frequently. We should definitely have super-diverse themes, and getting this foundation out and launched is the first step.

**Comment by nickhamze** [comment]
I thought so, but I thought I'd try. Thanks for the quick reply.

One note. Not everything that isn't _minimalistic_ and _clean_ is "weird".
