### ISSUE TITLE
Edited Navigation doesn't sync between the two header template parts

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#54]
In order to provide the reversed-out header for our front page template, we need to use two separate header template parts: 

`header-large-dark.html`|`header.html`
---|---
<img width="688" alt="Screen Shot 2021-10-07 at 11 59 37 AM" src="https://user-images.githubusercontent.com/1202812/136422342-b0d4f177-3e37-4103-97c1-77e384eb5483.png">|<img width="689" alt="Screen Shot 2021-10-07 at 12 05 20 PM" src="https://user-images.githubusercontent.com/1202812/136422344-adf14561-d59c-4721-8cad-96e401641622.png">

This is great and it works fine. Except for one thing: 

If you edit the navigation block on one of the two headers, they don't sync up. In general, I think they should — if someone were to edit their main navigation, they presumably want it to change everywhere on their site. 

I _think_ the best way to fix this today is to create another "Navigation" template part containing just the Navigation block, and place that new template part inside both of our header template parts. It's a little confusing, but I believe it'll solve the problem. 

Open to other suggestions!

**Comment by youknowriad** [comment]
I think that's good feedback for the team working on Navigation block as they're working on related flows. cc @talldan

**Comment by talldan** [comment]
Yep, very early exploration of this here - https://github.com/WordPress/gutenberg/pull/35418.
