### ISSUE TITLE
Site title link color is incorrect on the front end

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#58]
Flagging a followup from #55:

The Site Title color doesn't appear to inherit the correct white link color on the front end, even though it's properly set on the container. Seems like a likely Gutenberg bug, but could use more investigation. 

Editor|Front End
---|---
<img width="1246" alt="136429831-20926ff9-4434-4593-97a5-473b102399f0" src="https://user-images.githubusercontent.com/1202812/136457980-efd8b035-aac0-4096-ae3a-9dddf706cba6.png">|<img width="1246" alt="136429830-94de4e12-d685-4ff0-8f22-665000999e42" src="https://user-images.githubusercontent.com/1202812/136457984-7dda4fdd-cf8f-464d-9cba-74e4798a679b.png">

**Comment by carolinan** [comment]
I am actually seeing the white link color on the black background (front), and the black link color on the white background (inner pages) 🤔 

Current Gutenberg trunk, current theme trunk, Chrome, Windows. The only change I made was to add a logo since there is a logo in the screenshot above.

**Comment by jasmussen** [comment]
To only echo Carolina, I think this may have been fixed in latest trunk:
<img width="1726" alt="Screenshot 2021-10-08 at 10 06 32" src="https://user-images.githubusercontent.com/1204802/136521183-d97265e5-8029-4a22-8174-ef5b5c11b0ff.png">

**Comment by carolinan** [comment]
Ah yes https://github.com/WordPress/gutenberg/pull/35446

**Comment by kjellr** [comment]
I see it now too! 🙌

I'll mark as closed for now. Thanks everyone!
