### ISSUE TITLE
Tracking non-committer contributions

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/twentytwentytwo#59]
For past default themes, we have tried to include the list of people that contribute to discussions as well as code committers. There isn't really a good mechanism for that so trying to start compiling a list as early as possible might be a good idea.

**Comment by Otto42** [comment]
Maybe relevant.. since early development happens on GitHub, if everybody involved makes sure to connect their GH account to https://profiles.wordpress.org/ then that makes things a bit easier all around.

**Comment by jffng** [comment]
> trying to start compiling a list as early as possible might be a good idea.

Maybe we can make a PR to update https://github.com/WordPress/twentytwentytwo/blob/trunk/CONTRIBUTORS.md on a weekly basis?

**Comment by pattonwebz** [comment]
> > trying to start compiling a list as early as possible might be a good idea.
> 
> Maybe we can make a PR to update https://github.com/WordPress/twentytwentytwo/blob/trunk/CONTRIBUTORS.md on a weekly basis?

That sounds good to me, I am happy to take on that action and create those PRs every week on a Friday and try my best to keep it all updated with people that have both added code and also people that have contributed to the discussions :)

Could you assign this ticket to me and flag it as a WIP or something so it doesn't get closed?

**Comment by kjellr** [comment]
Thanks for your help, @pattonwebz!

**Comment by colorful-tones** [comment]
@pattonwebz are we still aiming for weekly updates on this?

**Comment by jeffpaul** [comment]
Is this still needed or has someone scanned for appropriate credits for the TT2 work?  If this is still open, then I can look to work on that into next week to get a current list of folks noted in the contributors file.

**Comment by jffng** [comment]
Thanks @jeffpaul, I [updated it](https://github.com/WordPress/twentytwentytwo/commit/cb51e537019b0efdc7d7db040de9d5d6c30ea487) this week since we committed the initial version of the theme to WordPress trunk. 

It would be good to double check though, and if you find any folks I missed feel free to open a PR to update the contributors list.

**Comment by jeffpaul** [comment]
@kjellr @jffng note the PR I submitted earlier to add missing props that I unearthed in reviewing merged PRs and their related issues.

**Comment by jffng** [comment]
Thank you @jeffpaul, I think we can close this one out since those contributors will now be added to the props in the core commit.
