### ISSUE TITLE
Add CSS reset

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/twentytwentytwo#61]
I know we're trying to keep CSS mostly out of the theme, but likely a reset will be necessary. Unless we want to try to do something more upstream: Gutenberg or WordPress core integration?

I would recommend Andy Bell's (@andy-piccalilli) [`modern-css-reset`](https://github.com/andy-piccalilli/modern-css-reset). 

Thoughts? Feedback?

**Comment by carolinan** [comment]
The upstream issue and discussions are here:
https://github.com/WordPress/gutenberg/issues/27116

https://github.com/WordPress/gutenberg/pull/27517#issuecomment-743181613
> Having a reset can break styles especially for things that are supposed to be "context agnostic". For example if you say `box-sizing: border-box` is part of the reset, blocks which styled are based on that assumption won't work on themes (or other contexts outside WP) that don't have that reset. For me, this kind of styles should be added to the blocks themselves and not assumed to be present. The theme shouldn't have to define the reset for these.

**Comment by colorful-tones** [comment]
@carolinan thanks for linking up those upstream conversations. Very helpful.

I feel like this could likely be elevated and recommended as a WordPress core feature alongside an option in `theme.json` for themes to opt in/out. 

I’m willing to attempt a Trac ticket if there is ample momentum and foreseeable need. Thoughts?

**Comment by carolinan** [comment]
It is not for me to decide -Can you show an issue that adding the reset would solve?

**Comment by colorful-tones** [comment]
> It is not for me to decide

I know. 👍 

> Can you show an issue that adding the reset would would solve?

My initial problem was the `margin` on the `body`, but it seems likely there is already a fix for that in the works upstream: https://github.com/WordPress/gutenberg/pull/35421/files

However my next potential candidate for solving with a reset would be enabling a better experience for end users with respecting their choice for animations, e.g.

```
/* Remove all animations and transitions for people that prefer not to see them */
@media (prefers-reduced-motion: reduce) {
  html:focus-within {
   scroll-behavior: auto;
  }
  *,
  *::before,
  *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
```

Yes, this presumes that animations are being used. Whether there is a significant number of themes that will likely use animation/transitions is relevant, and just trying to be forward thinking for end users _and_ theme developers.

**Comment by kjellr** [comment]
Yeah, I don't think this specific theme should bundle any sort of reset. If one is needed, it would theoretically benefit all themes.

**Comment by colorful-tones** [comment]
I'm trying to track down related Gutenberg or WP core tickets that may be related and provide coverage or solutions to address avoiding a CSS reset (on a line by line basis). 

I agree, that it would be ideal to keep this out of the theme, but would like to see some good coverage, and suspect that stuff like `html:focus-within` and `@media (prefers-reduced-motion: reduce)` stuff is a nice-to-have, worth discussing and collaborating toward a solution.

**Comment by colorful-tones** [comment]
The need for `body { margin: 0; }` in a CSS reset is likely addressed in upstream, recently merged (not in release yet) [Remove default padding/margin on the body of the page and editor canvas #35421](https://github.com/WordPress/gutenberg/pull/35421/files) <- needs testing and confirmation though.

**Comment by colorful-tones** [comment]
> The need for body { margin: 0; } in a CSS reset is likely addressed in upstream, recently merged (not in release yet) Remove default padding/margin on the body of the page and editor canvas #35421 <- needs testing and confirmation though.

I just tested this and confirm `body { margin: 0; }` upstream fix is making a desired impact on this theme. 👍

**Comment by colorful-tones** [comment]
After reflecting a bit more on this and synthesizing feedback. I think that my proposed reset is unnecessary. 

It is unlikely that this theme will not have any `animation` or `transition`, because of the drive to keep as much CSS out of the theme, and I do not see a drive to include `animation` or `transition` within the `theme.json`. So, justifying the need for the `@media (prefers-reduced-motion)` to disable animation for accessibility purposes is moot.

Similarly, adding `margin: 0` to most elements is mostly already handled on a per block basis upstream (in Gutenberg land).

The remaining lines in my proposed reset are mostly nice-to-haves, and do not seem critical to shipping this theme.

I'll leave this open for _now_, but please feel free to close. Thanks 😄

**Comment by kjellr** [comment]
Thanks for keeping tabs on this and following up, @colorful-tones! I think we can close this and the associated PR for now. We can always re-assess later if need be.

**Comment by ndiego** [comment]
@kjellr before opening a new ticket, I did want to point to another issue due to the lack of a reset. While extremely minor, the spacing on link blocks is not consistent between the editor and frontend. This is because `box-sizing: border-box;` is applied in the editor, but not on the frontend. I am sure there are other situations that are impacted by this. Perhaps this is more of a Gutenberg issue that could be solved there? 🤔

**Comment by MaggieCabrera** [comment]
> @kjellr before opening a new ticket, I did want to point to another issue due to the lack of a reset. While extremely minor, the spacing on link blocks is not consistent between the editor and frontend. This is because `box-sizing: border-box;` is applied in the editor, but not on the frontend. I am sure there are other situations that are impacted by this. Perhaps this is more of a Gutenberg issue that could be solved there? 🤔

That sounds like a Gutenberg issue to me, definitely
