### ISSUE TITLE
Built-in, optional support for microformats2?

### ISSUE THREAD

**Issue by reinhart1010** [WordPress/twentytwentytwo#78]
[microformats and microformats2](https://developer.mozilla.org/en-US/docs/Web/HTML/microformats) have existed for such a long time (first in 2005), and some people are still using it to allow their sites to be (semantically) discoverable by anyone.

My idea here is to sidechain a set of [microformats2](https://microformats.org/wiki/microformats2) class markups into the current set of WordPress-specific or theme-specific classes, like [`.e-content`](https://microformats.org/wiki/h-entry) alongside `.entry-content` (as in the Twenty Twenty One theme), `.h-card` with `a[rel="author"]`, `.p-category` alongside `a[rel="category"]` and `a[rel="tag"]`and so on.

I know that this would be redundant for such a theme, and not all site authors want their site to be discovered this way (i.e. by using microformats2), so I think it could be better to leave this as an optional feature, opt-in from the **Customize** menu that people have been familiar with.

At least it's better than [using a WordPress plugin](https://wordpress.org/plugins/wp-uf2/) which apparently breaks in some themes due to HTML string sanitation, including Twenty Twenty One.

**Comment by kjellr** [comment]
Thanks for the issue, @reinhart1010! I'm not personally too familiar with microformats, but this seems like something that would need to be added upstream Gutenberg rather than here in the theme. Since this is a block-based theme, it doesn't actually add its own markup for `entry-content`, categories, tags, etc. All of that is provided by the default Gutenberg blocks.

**Comment by scruffian** [comment]
Yeah, this would be great, but it needs to go in Gutenberg itself. You can open an issue for it in Gutenberg here: https://github.com/WordPress/gutenberg/issues/new/choose

**Comment by reinhart1010** [comment]
Before I forward this into Gutenberg: will Gutenberg also be responsible to handle how author names are displayed in this theme, let's say, for the [`.h-card`](http://microformats.org/wiki/h-card) markup?

**Comment by scruffian** [comment]
Yeah, that would use the Post Author block from Gutenberg.

**Comment by jffng** [comment]
Thanks for the issue @reinhart1010 , going to close this one since it should be handled in Gutenberg if there's support for it.
