### ISSUE TITLE
GB issue: Move the post title to the top bar

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwentytwo#86]
**Is your feature request related to a problem? Please describe.**

The post/page title is stuck in the layout. If a user wants to hide the title they will need to use CSS.

**Describe the solution you'd like**

The possibility to remove the title from the layout and instead add the Post Title block would create a lot of really nice flexibility as well as designs.

There is a PR that has gone stale that could use some feedback:
https://github.com/WordPress/gutenberg/pull/31288

**Comment by kjellr** [comment]
Hey @paaljoachim I don't think this is specifically related to the theme — it's Gutenberg UI. We should let this issue remain in Gutenberg and address it there.

**Comment by paaljoachim** [comment]
Hey @kjellr 

The reason why I added it here is that we can think of ways in which getting the PR merged can add suggestions to the new theme. That is also the reason why I added the other issue: https://github.com/WordPress/twentytwentytwo/issues/87

But I can always also close this issue.
