### ISSUE TITLE
GB issue: Allow using featured image as background

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwentytwo#87]
**Is your feature request related to a problem? Please describe.**

We are limited in how we show the featured image. There is a Featured Image block, but it is very limited in use.

**Describe the solution you'd like**

Allow using featured image as background in the Cover and Group block as well as other blocks. A general approach.
https://github.com/WordPress/gutenberg/issues/24660

**Comment by kjellr** [comment]
While it would make sense to allow for this, we won't be doing anything special in the theme to allow for it. We don't have any patterns planned that use this sort of treatment, so I don't think it makes sense to keep the issue open here for now. 

If that changes, we can reopen and move this issue to #75.
