### ISSUE TITLE
Footer Patterns: Followup Fixes

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#91]
Following #85, there are a couple small things that we should try and readdress for the footer patterns:

## Footer with query, title, and citation

- [x] Title and citation are oddly aligned on small screens. ([Screenshot](https://cloudup.com/ciMq4alVqwh))

## Footer with query, featured images, title, and citation

- [x] Title and citation are oddly aligned on small screens. ([Screenshot](https://cloudup.com/c7074k8_SBK))

## Dark footer with title and citation

- [ ] Title and citation have no left/right padding on small screens. ([Screenshot](https://cloudup.com/clwecooXWRw))

**Comment by carolinan** [comment]
I did not find a great solution for the dark footer with title and citation. Adding padding to the sides and not only top and bottom would mean the texts don't align with the content.
One alternative would be to center the texts.
