### ISSUE TITLE
Include the flying bird image in the homepage header

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#92]
The original mockup for the theme includes this flying bird image on the homepage template: 

<img width="622" alt="Screen Shot 2021-10-12 at 1 33 06 PM" src="https://user-images.githubusercontent.com/1202812/137002726-9d8d29ed-6fed-4a2e-994e-108cbbcecfa4.png">

This has been left out for now while we figure out the best way to include it. Here's the situation: 

Normally, we'd bundle this image in the theme files and refer to it in the PHP templates. This isn't possible in block templates, since the image block can't take a dynamic URL.  It will work fine in patterns though, where we can use PHP to find the right path. So a workaround like #56 may be possible.

We _could_ put it up on the WP.org CDN, or in the Pattern Directory's media library, and hotlink to it. But it feels non-ideal to have to require that 3rd-party request by default on the front-end. 

I think there's also something to be said about _not_ including this image here by default, since approx 99% of folks will not actually keep this bird image on the front page of their website. 😂

I'm opening this issue for discussion and to find a solution one way or another.

**Comment by carolinan** [comment]
Upstream issue: https://github.com/WordPress/gutenberg/issues/31815

**Comment by MaggieCabrera** [comment]
Well, if the pattern block actually ends up making it, that would solve it, right? A pattern block ends up being the solution to so many things!

**Comment by kjellr** [comment]
Yeah, the pattern block would solve it, but it seems like a weird workaround to me. 🤔

**Comment by kjellr** [comment]
This should now be possible by using the Pattern block. I'm changing this issue's title + tags as a result.
