### ISSUE TITLE
Buttons need hover, active, and focus states

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentytwo#99]
**Describe the bug**
Currently the buttons do not have hover, active, or focus states. ~Also it looks like their font weight is incorrect.~

**Screenshots**
Current | Desired
------- | --------
<img width="272" alt="Screen Shot 2021-10-13 at 9 16 06 AM" src="https://user-images.githubusercontent.com/5375500/137140442-f3efe364-0c08-48ad-b18b-39e24937939e.png"> | <img width="981" alt="Screen Shot 2021-10-13 at 9 15 27 AM" src="https://user-images.githubusercontent.com/5375500/137140464-2e8d57fe-1474-4f45-a91a-774d57557949.png">

**Comment by jffng** [comment]
Related upstream issue: https://github.com/WordPress/gutenberg/issues/27075

**Comment by jffng** [comment]
I started working on this a bit in the theme, and it helped to outline the considerations.

**Use cases to consider**
- User adjusts padding at the global level
- User adjusts padding at the block level
- User adjusts colors
- User selects the outline button style

**Challenges**
- The design uses a border in its hover state. We want to maintain consistent visual spacing between hover and resting states, i.e. the dimensions of the button shouldn't change between hover / resting. Ideally the default size of the button is the same between non-outline and outline buttons too. To do this, we need to calculate the padding value since it is different in hover vs resting state, and it depends on the border width.
- Global styles supplies padding values in-line when they are block-level customizations, but the styles are compiled into the `.wp-block-button__link` class when they are global customizations. Theme provided CSS is loaded after these customizations, making creating the right level of CSS specificity a challenge if we want to provide a default _and_ allow for the user to make global customizations to the button padding. See https://github.com/WordPress/gutenberg/issues/34141 for more context

**Comment by kjellr** [comment]
Just a heads up that [Gutenberg support for button hover states is no longer planned for 5.9](https://github.com/WordPress/gutenberg/issues/4543#issuecomment-958673190), so we'll need to make a call about whether or not to build something into the theme.  

I'll sum up my current thoughts here: 

- Overall, I'm not supportive of any complicated workarounds. Unfortunately, most theme-specific button CSS has historically been pretty complicated.  
- We've tried a number of solutions already (#162, #163, #168) and none feel satisfactory yet. 
- @jffng and I are also weighing the option of _not_ including hover states at all (as described in https://github.com/WordPress/gutenberg/issues/4543#issuecomment-954863058). I don't love this approach either. 

I haven't made up my mind one way or another yet, but in general, it seems clear that we have a bunch of non-ideal options to choose from.

**Comment by carolinan** [comment]
It is so much easier to only style one button. The other variations can be deregistered 🤐

**Comment by paaljoachim** [comment]
Can we perhaps get it into a WP 5.9.1 theme update instead?

**Comment by kjellr** [comment]
We haven't updated this in a while, so just adding a few notes from various slack conversations: 

- @jffng and I have been leaning towards _not_ adding button hover states. The previous explorations linked above have all been too complicated, or haven't looked great. Users will able to add their own hover states when Gutenberg supports this. 
- We've had mixed signals on whether or not that would be ok from an a11y perspective though. On one hand, WCAG does not _require_ hover states for buttons. But on the other hand, it's better to do it. Also, these are actually just links styled up to look like buttons.
- If we did implement something, maybe a simple opacity change would take care of this and also not interfere too much with future Gutenberg features.
